### ISSUE TITLE
Class constant accessed from instance causes NullReferenceException

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#100]
See the following usage of a PHP class constant:
```php
<?php
class A
{
  const A_CONST = 42;
}
function test($a) {
  echo $a::A_CONST;
}
test(new A);
```
PHP returns ```42```, our runtime currently throws a runtime exception:
```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Peachpie.Runtime
  StackTrace:
   at Pchp.Core.Reflection.TypeMembersUtils.GetDeclaredConstant(PhpTypeInfo tinfo, String name) in C:\iolevel\peachpie\src\Peachpie.Runtime\Reflection\TypeMembersUtils.cs:line 412
   at Pchp.Core.Dynamic.BinderHelpers.BindClassConstant(PhpTypeInfo type, Type classCtx, String constName, Expression ctx) in C:\iolevel\peachpie\src\Peachpie.Runtime\Dynamic\BinderHelpers.cs:line 640
   at Pchp.Core.Dynamic.GetFieldBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args) in C:\iolevel\peachpie\src\Peachpie.Runtime\Dynamic\GetFieldBinder.cs:line 90
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at <Root>..\\..\\..\\..\\..\\..\\tests/constants.constants_003_php.test(Context <ctx>, PhpValue a) in C:\iolevel\peachpie\tests\constants\constants_003.php:line 9
   at <Root>..\\..\\..\\..\\..\\..\\tests/constants.constants_003_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\iolevel\peachpie\tests\constants\constants_003.php:line 12
   at <Root>..\\..\\..\\..\\..\\..\\tests/constants.constants_003_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self) in C:\iolevel\peachpie\src\Peachpie.Runtime\Context.ScriptsMap.cs:line 82
   at Peachpie.Library.Scripting.Script.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self) in C:\iolevel\peachpie\src\Peachpie.Library.Scripting\Context.Script.cs:line 278
   at ScriptsTest.ScriptsTest.CompileAndRun(String path) in C:\iolevel\peachpie\src\Tests\Peachpie.ScriptTests\ScriptsTest.cs:line 80
   at ScriptsTest.ScriptsTest.ScriptRunTest(String dir, String fname) in C:\iolevel\peachpie\src\Tests\Peachpie.ScriptTests\ScriptsTest.cs:line 35
```
It occurs when ```tinfo.Type.GetInterfaces()``` is accessed in ```TypeMembersUtils.GetDeclaredConstant()``` (```tinfo``` is ```null```).

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/88a902876339da7d5dc2d53eecbfa1cd0f931056
