### ISSUE TITLE
.net 5:CodeBase is not supported on assemblies loaded from a single-file bundle

### ISSUE THREAD

**Issue by avriltank** [peachpiecompiler/peachpie#1003]
```
Application startup exception: System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetNormalizedCodeBasePath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetDepsJsonPath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly, IDependencyContextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.LoadDefault()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.LoadScriptAssemblies(PhpOptions options)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware..ctor(RequestDelegate next, IHostingEnvironment hostingEnv, IServiceProvider services, PhpHandlerConfiguration configuration)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
```
The problem occurred in **Net5 or above**, which is a comparison of Microsoft's official website Net core[ URL link](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/assembly-api-behavior-changes-for-single-file-publish)

**Comment by jakubmisek** [comment]
thank you, may I ask for more details? What was the `Assembly assembly` if you check the Locals when this happens.

**Comment by avriltank** [comment]
Sorry, I don't quite understand what you mean! This is my command to issue a single file:

`dotnet publish -c release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true --self-contained true -o publish_ dir_ win_ single.`

For the source code of peachpie, I haven't had time to read it! I think it seems that the incompatibility problem is caused by the code shown in the figure below:
![one](https://user-images.githubusercontent.com/13652682/146676694-0e65480f-2904-4471-ac1f-718d7787fbc6.png)
![two](https://user-images.githubusercontent.com/13652682/146676774-7004b71d-75ad-42ec-b3f9-43af4bee105c.png)

**Comment by jakubmisek** [comment]
The exception is thrown by [DeendencyContext.Default](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencymodel.dependencycontext.default?view=dotnet-plat-ext-5.0).

I have found a workaround on stackoverflow at
https://stackoverflow.com/questions/64818343/publishing-error-for-single-file-net-5-project-due-to-3rd-party-dependencies

Although from the exception it seems, `/p:PublishSingleFile=true` won't allow us to do what we want to do :) I'll try to workaround it. For now, ommiting `PublishSingleFile` might help.

**Comment by avriltank** [comment]
Thanks for you!This is a great project that will have high performance Net and simple and fast PHP. I'm trying to learn it and introducing it to my friends At least now it performs very well in synchronous code, and I look forward to the asynchronous feature

**Comment by jakubmisek** [comment]
thank you!

**Comment by vvtll** [comment]
There is no result when build an single exe for .net core web project!

**Comment by avriltank** [comment]
> There is no result when i build a single exe for .net core web project!

Hi,You should add script reference for your php library when publish a single file
