### ISSUE TITLE
Peachpie crypt behavior

### ISSUE THREAD

**Issue by hey-red** [peachpiecompiler/peachpie#1110]
php crypt can successfully generate hash if password length lower than 8, but peachpie throws an exception:

```C#
System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at System.String.get_Chars(Int32 index)
         at Pchp.Library.Strings.DES.Crypt(String password, String setting)
         at Pchp.Library.Strings.crypt(String str, String salt)
```

Example code:

```php
<?php
echo crypt("passwor", "as"); // => asMCHF81kwrKs
```

**Comment by jakubmisek** [comment]
thank you for reporting the issue!
