### ISSUE TITLE
Peachpie.Library.XmlDom.XMLWriter: Error writing namespace attribute 'xmlns'

### ISSUE THREAD

**Issue by wujwmail** [peachpiecompiler/peachpie#1142]
Running error message:

```
        Unhandled exception. System.Xml.XmlException: The prefix '' cannot be redefined from '' to 'http://schemas.openxmlformats.org/package/2006/content-types' within the same start element tag.
           at System.Xml.XmlWellFormedWriter.PushNamespaceExplicit(String prefix, String ns)
           at System.Xml.XmlWellFormedWriter.WriteEndAttribute()
           at Peachpie.Library.XmlDom.XMLWriter.<>c__DisplayClass41_0.<writeAttribute>b__2()
           at Peachpie.Library.XmlDom.XMLWriter.CheckedCall(Action operation)
           at Peachpie.Library.XmlDom.XMLWriter.writeAttribute(String name, String content)
           ....
```

PHPExcel source code (PHPExcel-1.8.1):  https://github.com/PHPOffice/PHPExcel

\PHPExcelPhpCsLib\PHPExcel\Writer\Excel2007\ContentTypes.php:line 61
This statement seems to be wrong:

         $objWriter->writeAttribute('xmlns', 'http://schemas.openxmlformats.org/package/2006/content-types');
[Uploading PHPExcel_test.zip…]()

**Comment by wujwmail** [comment]
## C# test Peachpie.Library.XmlDom.XMLWriter
```       
       using System;
       using Pchp.Core;
       using Peachpie.Library.XmlDom;
       ......
        static void Main(string[] args)
        {
            Context ctx = Context.CreateConsole(null, args);
            XMLWriter xw = new XMLWriter();
            xw.openMemory(ctx);
            xw.startElement("element");
            xw.writeAttribute("xmlns", "http://schemas.openxmlformats.org/package/2006/content-types");
           // xw.writeAttribute("not_xmlns", "http://schemas.openxmlformats.org/package/2006/content-types");
            xw.endElement();
            Console.WriteLine(xw.flush());
            Console.ReadLine();
        }
```

**Comment by wujwmail** [comment]
## Solve the program segment with special attribute name "xmlns" in C#
```
            System.Xml.XmlWriterSettings settings = new System.Xml.XmlWriterSettings();
            settings.Indent = true;

            using (var writer = System.Xml.XmlWriter.Create(Console.Out, settings))
            {
                writer.WriteStartElement("element", "http://schemas.openxmlformats.org/package/2006/content-types");
                // Write other elements and attributes
                writer.WriteAttributeString("other", "123");
                writer.WriteEndElement();
            }
```

###  The result of running the program is:
```
    <element other="123" xmlns="http://schemas.openxmlformats.org/package/2006/content-types" />
```

**Comment by jakubmisek** [comment]
`XmlTextWriter` seems to work ok.

Do you think it's compatible with `XmlWriter`?

**Comment by wujwmail** [comment]
XmlTextWriter inherits from XmlWriter and can be replaced by XmlTextWriter. However, there is a small problem that the XmlWriterSettings class cannot be injected. Let me try and see if there is a way to solve it?

**Comment by jakubmisek** [comment]
I see! the missing XmlSettings might be a problem :/

**Comment by wujwmail** [comment]
This problem has been solved using XmlTextWriter! For details, see: https://github.com/peachpiecompiler/peachpie/pull/1140

**Comment by mindfocus** [comment]
#1140 can also solve #761? @wujwmail
