### ISSUE TITLE
error MSB3073: exit code -532462766 Wordpress 4.9.2

### ISSUE THREAD

**Issue by fpierrat75** [peachpiecompiler/peachpie#146]
I'm trying to compile version 4.9.3 of Wordpress, I've removed all compilation errors, there is one last thing I can't get rid of.

Below is the stacktrace. Do you have any idea?

Thanks

```
D:\peachpie-wordpress-master\website\wp-includes\nav-menu.php(983,52): warning PHPX0125: Mandatory parameter '$tt_id' declared behind optional parameter
D:\peachpie-wordpress-master\website\wp-includes\nav-menu.php(983,60): warning PHPX0125: Mandatory parameter '$taxonomy' declared behind optional parameter
D:\peachpie-wordpress-master\website\wp-includes\SimplePie\Locator.php(94,54): warning PHPX0125: Mandatory parameter '$working' declared behind optional parameter

Unhandled Exception: System.ArgumentException: Fatal error: Access level to $message must be Protected (as in class Exception)
   at Pchp.CodeAnalysis.Symbols.SourceFieldSymbol.get_OriginalDefinition()
   at Pchp.CodeAnalysis.CodeGen.FieldPlace..ctor(IPlace holder, IFieldSymbol field, PEModuleBuilder module)
   at Pchp.CodeAnalysis.Symbols.SourceFieldSymbol.Pchp.CodeAnalysis.Symbols.IPhpPropertySymbol.EmitInit(CodeGenerator cg)
   at Pchp.CodeAnalysis.Symbols.SourceTypeSymbol.<>c__DisplayClass3_1.<EmitPhpCtors>b__0(ILBuilder il)
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
   at Pchp.CodeAnalysis.Symbols.SourceTypeSymbol.EmitPhpCtors(ImmutableArray`1 instancectors, PEModuleBuilder module, DiagnosticBag diagnostics)
   at Pchp.CodeAnalysis.Symbols.SourceTypeSymbol.EmitInit(PEModuleBuilder module, DiagnosticBag diagnostics)
   at Devsense.PHP.Syntax.CollectionUtils.Foreach[T](IEnumerable`1 enumerable, Action`1 action)
   at Pchp.CodeAnalysis.SourceCompiler.EmitSynthesized()
   at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
C:\Users\frederic.pierrat\.nuget\packages\peachpie.net.sdk\0.9.0-ci00666\build\Peachpie.NET.Core.Sdk.targets(148,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netstandard1.6\compile-php-args.rsp" exited with code -532462766.
Done building project "website.msbuildproj" -- FAILED.
```

**Comment by fpierrat75** [comment]
Well done, I found the culprit.  

wp-includes\ID3\getid3.php ligne1841

```
class getid3_exception extends Exception
{
	public $message;
}
```

worpress run now 👍  Thank you very much
