### ISSUE TITLE
Error while compiling barcode generator class

### ISSUE THREAD

**Issue by TyKonKet** [peachpiecompiler/peachpie#148]
I'm trying to build this barcode generator class:
[https://gist.github.com/TyKonKet/62c6b5dc4563974b8b37d27644d3df09](https://gist.github.com/TyKonKet/62c6b5dc4563974b8b37d27644d3df09)

But I get this error:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Pchp.CodeAnalysis.Semantics.BoundVariableRef.Place(ILBuilder il)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.TryEmitVariableSpecialize(BoundExpression expr)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitSpecialize(BoundExpression expr)
   at Pchp.CodeAnalysis.CodeGen.DynamicOperationFactory.CallSiteData.EmitArg(BoundArgument a)
   at Pchp.CodeAnalysis.CodeGen.DynamicOperationFactory.CallSiteData.EmitArgs(ImmutableArray`1 args)
   at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.EmitCallsiteCall(CodeGenerator cg)
   at Pchp.CodeAnalysis.Semantics.BoundGlobalFunctionCall.EmitDynamicCall(CodeGenerator cg)
   at Pchp.CodeAnalysis.Semantics.BoundExpressionStatement.Emit(CodeGenerator cg)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.Semantics.Graph.SwitchEdge.Generate(CodeGenerator cg)
   at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Generate(CodeGenerator cg)
   at Pchp.CodeAnalysis.Semantics.Graph.StartBlock.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
   at Pchp.CodeAnalysis.Symbols.SourceRoutineSymbol.Generate(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
   at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBody(SourceRoutineSymbol routine)
   at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func)
   at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
```

**Comment by jakubmisek** [comment]
thanks! the issue has been fixed
