### ISSUE TITLE
Getting IndexOutOfRangeException when trying to compile

### ISSUE THREAD

**Issue by Valks** [peachpiecompiler/peachpie#149]
As per the title I'm getting an IndexOutOfRangeException exception from the compiler.
```
 Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
     at Pchp.CodeAnalysis.Semantics.Graph.ControlFlowGraph.GetLocalTypeMask(String varname)
     at Pchp.CodeAnalysis.Symbols.SourceLocalSymbol.get_Type()
     at Pchp.CodeAnalysis.Semantics.BoundLocal.EmitInit(CodeGenerator cg)
     at Pchp.CodeAnalysis.Semantics.Graph.StartBlock.Emit(CodeGenerator cg)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
     at Pchp.CodeAnalysis.Symbols.SourceRoutineSymbol.Generate(CodeGenerator cg)
     at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
     at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBody(SourceRoutineSymbol routine)
     at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func)
     at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
C:\Users\<user>\.nuget\packages\peachpie.net.sdk\0.9.0-ci00672\build\Peachpie.NET.Core.Sdk.targets(148,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netstandard2.0\compile-php-args.rsp" exited with code -532462766. [C:\repos\website\website.msbuildproj]
```

**Comment by jakubmisek** [comment]
I have found a test case:
```php
function foo() {
	return;
	static $p;
}
```

**Comment by jakubmisek** [comment]
Should be fixed now, please reopen if you have anonther test case.
