### ISSUE TITLE
Timezone fails to resolve

### ISSUE THREAD

**Issue by Valks** [peachpiecompiler/peachpie#150]
Ran into an issue called date_create when I passed in a timezone value of Australia/Melbourne. Trying US/Central works. It looks like not all the timezones are implemented.

List of timezones: http://php.net/manual/en/timezones.php

```
$dateToConvert = '2018-01-21 12:10:20';
$tz = 'Australia/Melbourne';
$datetime = date_create( $dateToConvert, new DateTimeZone( $tz ) );
```

```
Exception has occurred: CLR/System.ArgumentException
An exception of type 'System.ArgumentException' occurred in Peachpie.Library.dll but was not handled in user code: 'Value does not fall within the expected range.'
   at Pchp.Library.DateTime.DateTimeZone.__construct(String timezone_name)
   at <Root>wp-includes.formatting_php.get_gmt_from_date(Context <ctx>, PhpValue string, PhpValue format) in c:\website\wp-includes\formatting.php:line 3014
   at WC_Data.set_date_prop(PhpValue prop, PhpValue value) in c:\website\wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-data.php:line 718
   at WC_Customer.set_date_created(PhpValue date) in c:\website\wp-content\plugins\woocommerce\includes\class-wc-customer.php:line 783
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at WC_Data.set_props(PhpValue props, PhpValue context) in c:\website\wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-data.php:line 606
   at WC_Customer_Data_Store.read(PhpAlias customer) in c:\website\wp-content\plugins\woocommerce\includes\data-stores\class-wc-customer-data-store.php:line 158
   at WC_Data_Store.read(PhpAlias data) in c:\website\wp-content\plugins\woocommerce\includes\class-wc-data-store.php:line 147
   at WC_Customer.__construct(PhpValue data, PhpValue is_session) in c:\website\wp-content\plugins\woocommerce\includes\class-wc-customer.php:line 106
   at WC_Customer..ctor(Context <ctx>, PhpValue data, PhpValue is_session)
   at WooCommerce.init() in c:\website\wp-content\plugins\woocommerce\includes\class-woocommerce.php:line 457
   at Pchp.Core.PhpCallableExtension.<>c__DisplayClass0_0.<Bind>b__0(Context ctx, PhpValue[] arguments)
   at Pchp.Core.PhpCallback.Invoke(Context ctx, PhpValue[] arguments)
   at Pchp.Library.Functions.call_user_func(Context ctx, IPhpCallable function, PhpValue[] args)
   at Pchp.Library.Functions.call_user_func_array(Context ctx, IPhpCallable function, PhpArray args)
   at WP_Hook.apply_filters(PhpValue value, PhpValue args) in c:\website\wp-includes\class-wp-hook.php:line 286
   at WP_Hook.do_action(PhpValue args) in c:\website\wp-includes\class-wp-hook.php:line 310
   at <Root>wp-includes.plugin_php.do_action(Context <ctx>, PhpValue tag, PhpValue arg, PhpValue[] <arguments>) in c:\website\wp-includes\plugin.php:line 455
   at <Root>.wp-settings_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in c:\website\wp-settings.php:line 453
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.wp-config_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in c:\website\wp-config.php:line 181
   at <Root>.wp-config_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.wp-load_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in c:\website\wp-load.php:line 37
   at <Root>.wp-load_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.wp-blog-header_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in c:\website\wp-blog-header.php:line 13
   at <Root>.wp-blog-header_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in c:\website\index.php:line 17
   at <Root>.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.Web.PhpHandlerMiddleware.<>c__DisplayClass6_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by jakubmisek** [comment]
Right, currently we use timezones provided by .NET. They have basically just a different names.

We'll define PHP-like names.

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/35685d772e7a859c5732697d0ba278b0d1ad1ea1
