### ISSUE TITLE
function 'mb_list_encodings()' not implements

### ISSUE THREAD

**Issue by Valks** [peachpiecompiler/peachpie#152]
Ran into an issue with ```mb_list_encodings()``` raised a System.ArgumentException.

http://php.net/manual/en/function.mb-list-encodings.php

The module: http://simplepie.org/ which comes with WordPress uses ```mb_list_encodings()```

```
// Check that the encoding is supported
		if (@mb_convert_encoding("\x80", 'UTF-16BE', $input) === "\x00\x80")
		{
			return false;
		}
		if (!in_array($input, mb_list_encodings()))
```

```
Exception has occurred: CLR/System.ArgumentException
An exception of type 'System.ArgumentException' occurred in Peachpie.Runtime.dll but was not handled in user code: 'Function 'mb_list_encodings' not found!'
   at Pchp.Core.Dynamic.CallBinder.BindMissingMethod(CallSiteContext bound)
   at Pchp.Core.Dynamic.CallBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at SimplePie_Misc.change_encoding_mbstring(Context <ctx>, PhpValue data, PhpValue input, PhpValue output) in c:\website\wp-includes\SimplePie\Misc.php:line 356
   at SimplePie_Misc.change_encoding(Context <ctx>, PhpValue data, PhpValue input, PhpValue output) in c:\website\wp-includes\SimplePie\Misc.php:line 316
   at Pchp.Core.Reflection.PhpMethodInfo.Invoke(Context ctx, Object target, PhpValue[] arguments)
   at Pchp.Core.Reflection.PhpMethodInfo.<get_PhpCallable>b__14_0(Context ctx, PhpValue[] args)
   at Pchp.Core.PhpCallback.Invoke(Context ctx, PhpValue[] arguments)
   at Pchp.Library.Functions.call_user_func(Context ctx, IPhpCallable function, PhpValue[] args)
   at Pchp.Library.Functions.call_user_func_array(Context ctx, IPhpCallable function, PhpArray args)
   at SimplePie_Registry.call(PhpValue type, PhpValue method, PhpValue parameters) in c:\website\wp-includes\SimplePie\Registry.php:line 222
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at SimplePie<>.init() in c:\website\wp-includes\class-simplepie.php:line 1379
   at <Root>wp-includes.feed_php.fetch_feed(Context <ctx>, PhpValue url) in c:\website\wp-includes\feed.php:line 703
   at <Root>wp-includes.widgets_php.wp_widget_rss_output(Context <ctx>, PhpValue rss, PhpValue args) in c:\website\wp-includes\widgets.php:line 1388
   at reduxDashboardWidget<>.redux_dashboard_widget() in c:\website\wp-content\plugins\redux-framework\ReduxCore\core\dashboard.php:line 34
   at Pchp.Core.PhpCallableExtension.<>c__DisplayClass0_0.<Bind>b__0(Context ctx, PhpValue[] arguments)
   at Pchp.Core.PhpCallback.Invoke(Context ctx, PhpValue[] arguments)
   at Pchp.Library.Functions.call_user_func(Context ctx, IPhpCallable function, PhpValue[] args)
   at <Root>wp-admin/includes.template_php.do_meta_boxes(Context <ctx>, PhpValue screen, PhpValue context, PhpValue object) in c:\website\wp-admin\includes\template.php:line 1063
   at <Root>wp-admin/includes.dashboard_php.wp_dashboard(Context <ctx>) in c:\website\wp-admin\includes\dashboard.php:line 221
   at <Root>wp-admin.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in c:\website\wp-admin\index.php:line 135
   at <Root>wp-admin.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.Web.PhpHandlerMiddleware.<>c__DisplayClass6_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/eb1e544c07a18c51000cf679f2eb06aeab73365a with basic set of .NET encodings
