### ISSUE TITLE
PDO how to use

### ISSUE THREAD

**Issue by Seimann91** [peachpiecompiler/peachpie#154]
Hey,
how can I use PDO?
I always get the error: Peachpie.Library.PDO.PDOException: "Driver 'mysql' not found"

I create a new template with:
`dotnet new web -lang PHP`
In index.php:
`$pdo = new PDO('mysql:host=localhost;dbname=testdb', 'root', 'rootpw');
...`

Sorry I'm new to .Net and like Peachpie, I want to learn more to use it!
best regards

**Comment by jakubmisek** [comment]
Hi, good question!

Currently, PDO drivers are not enabled by default.

Edit your `.msbuildproj` file, and add following into `<ItemGroup>` section together with other `<PackageReference>` elements:
```xml
<PackageReference Include="Peachpie.Library.PDO.MySQL" Version="0.9.0-*" />
```

**Comment by Seimann91** [comment]
thank you very much @jakubmisek !

**Comment by Seimann91** [comment]
Sorry, but now i get the error:
index.php
`$pdo = new PDO('mysql:host=localhost;dbname=testdb', 'root', 'rootpw');`
**System.ArgumentException: "Keyword not supported."**
System.ArgumentException
  HResult=0x80070057
  Nachricht = Keyword not supported.
  Quelle = MySql.Data
  Stapelüberwachung:
   at MySql.Data.MySqlClient.MySqlConnectionStringBuilder.GetOption(String key)
   at MySql.Data.MySqlClient.MySqlConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at MySql.Data.MySqlClient.MySqlConnectionStringBuilder..ctor(String connStr)
   at Peachpie.Library.PDO.MySQL.PDOMySQLDriver.BuildConnectionString(String dsn, String user, String password, PhpArray options)
   at Peachpie.Library.PDO.PDODriver.OpenConnection(String dsn, String user, String password, PhpArray options)
   at Peachpie.Library.PDO.PDO.__construct(String dsn, String username, String password, PhpArray options)
   at <Root>.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Projekte\Core\Website\index.php:line 3
   at <Root>.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.Web.PhpHandlerMiddleware.<>c__DisplayClass6_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

what am I doing wrong?

**Comment by jakubmisek** [comment]
I see. We did not make the connection string compatible with both PHP/.NET yet.

.NET MySQL driver does not recognize `host` and `dbname` keywords. It seems their equivalents are `server` and `database`, so the connection string should be:
`mysql:server=localhost;database=testdb`

Support for backward compatible legacy PHP keywords will be added.

**Comment by Seimann91** [comment]
Thanks connection works, but
i cant use execute() and query() with PDO
**System.NotImplementedException: "The method or operation is not implemented."**
`$pdo->query($sql)`
`$statement->execute()`

**Comment by jakubmisek** [comment]
we have added few more features to PDO at https://github.com/peachpiecompiler/peachpie/commit/90f021d80f6557e49f982232bfbac9d4668d3beb
including `PDO::query`

**Comment by jakubmisek** [comment]
Closing this one. Please open an issue for anything new :)
