### ISSUE TITLE
having trouble making extension that registers in the PHP context

### ISSUE THREAD

**Issue by laytondavis** [peachpiecompiler/peachpie#161]
I have a PHP application that I cannot change to use PDO. It is using ODBC/Postgres.

I have copied heavily from the MySQL runtime to make a postgres extension. I have enough of the environment working that I can reliably call the different postgres functions. The problem is that it is never creating the configuration in the context.

at the beginning of the MySQL class is this header:
```csharp
[PhpExtension("mysql", Registrator = typeof(Registrator))]
    public static partial class MySql
    {
        sealed class Registrator
        {
            public Registrator()
            {
                Context.RegisterConfiguration(new MySqlConfiguration());
                MySqlConfiguration.RegisterLegacyOptions();
            }
        }
```

Here is what I have:
```csharp
[PhpExtension("Postgres", Registrator = typeof(Registrator))]
    public static class Postgres {
        sealed class Registrator {
            public Registrator() {
                // will fill this in later
                // this class sets up global PHP configuration stuff
                Context.RegisterConfiguration(new PostgresConfiguration());
                PostgresConfiguration.RegisterLegacyOptions();
            }
        }
```

It looks like the runtime should instantiate the Registrator class and call the constructor. This looks like some semblance of a constructor for the static class since it normally does not have one. How does this get called? and how do I link into that with my postgres extension?

PS. I just pulled from git and rebuilt everything and am still having this behavior.

**Comment by jakubmisek** [comment]
I agree that `PhpExtension` with `Registrator` was not yet well specified.

This is only getting invoked when the class contains some PHP functions like
```csharp
public static int some_function() => 123;
```

**Comment by laytondavis** [comment]
then this should qualify, along with 9 others that are in that class. I can call into these functions from PHP. I know that this is happening because I can step into those functions in the debugger. The only issue is that the registrator isn't getting called. If I call it manually from inside this function as shown in the sample code below, then it does work, so I know that this is the cause of the problem.

public static PhpResource pg_connect(Context ctx, string connstring, int conType = 0) {
			bool new_link = true;
			if (conType != 0) {
				new_link = false;
			}
			var config = ctx.Configuration.Get<PostgresConfiguration>();
// When I do this, it works.
// But I wouldn't think I should need to with the line that is above the class definition
if (config == null) {
	var register = new Registrator(); // I think all I want is to call the constructor
	config = ctx.Configuration.Get<PostgresConfiguration>();
}
			Debug.Assert(config != null);

			bool success;
			var connection = PostgresConnectionManager.GetInstance(ctx)
				.CreateConnection(connstring, new_link, -1, out success);

			if (!success) { 
				connection = null;
			}

			return connection;
		}

**Comment by jakubmisek** [comment]
the registrator gets activated on https://github.com/peachpiecompiler/peachpie/blob/master/src/Peachpie.Runtime/Reflection/ExtensionsTable.cs#L213

it really should get called, are you able to debug it ?

**Comment by jakubmisek** [comment]
Do you see your extension in `get_loaded_extensions()` ?

**Comment by laytondavis** [comment]
no, there are no extensions loaded. The dll is not getting loaded until PHP is calling pg_connect. With a breakpoint in the registrator, that is not getting called until I call it.

Is there an initialization step I am missing? I am compiling the PHP as a dll, then I am creating a context, and then instantiating a php class, and then calling into the class.

It shouldn't make any difference, but I am calling this all from electron.js through an edge.js bridge between javascript and c#. Then the c# is calling into PHP. I can see that whatever gets set up in one call into PHP is still there on the next call.

**Comment by jakubmisek** [comment]
I see! The API is not yet final, but you have to initialize Context once (https://github.com/iolevel/peachpie-samples/blob/master/csharp-php-hybrid/csharpapp/Program.cs#L13) to load referenced libraries, functions etc. This should do the trick.

**Comment by laytondavis** [comment]
that does load the dll, but it still isn't doing the initialization that I would expect.

**Comment by jakubmisek** [comment]
Basically calling `AddScriptReference(your_php_assembly)` declares all the referenced libraries including yours into Context (application wide). It is pretty straightforward, if you can, please add breakpoint into `AddScriptReference` and `ExtensionsTable.AddRoutine` which handles your `Registrator`

**Comment by laytondavis** [comment]
With peach compiled for Release I can tell that AddScriptReference is being called, but I can't tell what the contents are. So I tried compiling for Debug. Now when I try to compile my PHP I am getting this dump -- and it doesn't seem to matter which build I am using

```
Unhandled Exception: System.InvalidOperationException: Unexpected value 'PhpValue' of type 'Pchp.CodeAnalysis.Symbols.PENamedTypeSymbol+PENamedTypeSymbolNonGeneric'
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitCastToFalse(TypeSymbol stack, Boolean deepcopy) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Emit.cs:line 1607
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitMethodAccess(TypeSymbol stack, MethodSymbol method, BoundAccess access) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Emit.cs:line 1513
   at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.EmitDirectCall(CodeGenerator cg, ILOpCode opcode, MethodSymbol method, BoundTypeRef staticType) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundExpression.cs:line 2362
   at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.Emit(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundExpression.cs:line 2337
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitSpecialize(BoundExpression expr) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Emit.cs:line 308
   at Pchp.CodeAnalysis.Semantics.BoundAssignEx.Emit(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundExpression.cs:line 3021
   at Pchp.CodeAnalysis.Semantics.BoundExpressionStatement.Emit(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundStatement.cs:line 47
   at Pchp.CodeAnalysis.Semantics.BoundStatement.Pchp.CodeAnalysis.CodeGen.IGenerator.Generate(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundStatement.cs:line 23
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.Generate(IGenerator element) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.cs:line 495
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Emit(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundBlock.cs:line 22
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Pchp.CodeAnalysis.CodeGen.IGenerator.Generate(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundBlock.cs:line 29
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateBlock(BoundBlock block) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.cs:line 486
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.LocalScope.ContinueWith(BoundBlock block) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.cs:line 134
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.cs:line 453
   at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Generate(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundEdge.cs:line 83
   at Pchp.CodeAnalysis.Semantics.Graph.Edge.Pchp.CodeAnalysis.CodeGen.IGenerator.Generate(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundEdge.cs:line 24
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Emit(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundBlock.cs:line 20
   at Pchp.CodeAnalysis.Semantics.Graph.StartBlock.Emit(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundBlock.cs:line 119
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Pchp.CodeAnalysis.CodeGen.IGenerator.Generate(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundBlock.cs:line 29
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateBlock(BoundBlock block) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.cs:line 486
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.LocalScope.ContinueWith(BoundBlock block) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.cs:line 134
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.cs:line 453
   at Pchp.CodeAnalysis.Symbols.SourceRoutineSymbol.Generate(CodeGenerator cg) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\Symbols\SourceRoutineSymbol.cs:line 121
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.<>c__DisplayClass1_0.<GenerateMethodBody>b__0(ILBuilder builder) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\MethodGenerator.cs:line 65
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\MethodGenerator.cs:line 98
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, SourceRoutineSymbol routine, Int32 methodOrdinal, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb) in G:\peachpie\src\Peachpie.CodeAnalysis\CodeGen\MethodGenerator.cs:line 38
   at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBody(SourceRoutineSymbol routine) in G:\peachpie\src\Peachpie.CodeAnalysis\Compilation\SourceCompiler.cs:line 224
   at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func) in G:\peachpie\src\Peachpie.CodeAnalysis\Utilities\EnumeratorExtension.cs:line 63
   at Pchp.CodeAnalysis.SourceCompiler.WalkMethods(Action`1 action) in G:\peachpie\src\Peachpie.CodeAnalysis\Compilation\SourceCompiler.cs:line 55
   at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBodies() in G:\peachpie\src\Peachpie.CodeAnalysis\Compilation\SourceCompiler.cs:line 192
   at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken) in G:\peachpie\src\Peachpie.CodeAnalysis\Compilation\SourceCompiler.cs:line 312
   at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in G:\peachpie\src\Peachpie.CodeAnalysis\Compilation\PhpCompilation.cs:line 792
   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Pchp.CodeAnalysis.CommandLine.Program.Main(String[] args) in G:\peachpie\src\Compiler\peach\Program.cs:line 13
```

**Comment by laytondavis** [comment]
the command I am issuing that gets the dump in the last message
`peach /t:library /debug+ /r:peachpiePostgres.dll /out:peachfrn.dll ../**/*.php ../shared/**/*.php`

**Comment by laytondavis** [comment]
there seems to be a data type in my dll that is no longer matching what peachpie is expecting.

**Comment by laytondavis** [comment]
ok, Got it all working again. 
`AddScriptReference` is getting called when I call it in my initialization code.
`ExtensionsTable.AddRoutine` is never getting called.

**Comment by jakubmisek** [comment]
a) `Unexpected value 'PhpValue'` is caused by having `[return: CastToFalse]` above a function that returns `PhpValue`. This attributed only applies on return types `int`, `long` and reference types.

b) does your library contain [assembly: PhpExtension] ?

**Comment by laytondavis** [comment]
yes.
`[assembly: Pchp.Core.PhpExtension("Postgres")]`

**Comment by jakubmisek** [comment]
`ExtensionsTable.AddRoutine` should get called like 4 hundred times, for each function defined in referenced libraries. It also handled the `Registrator` instantiation.

**Comment by laytondavis** [comment]
calling AddScripotReference with the peachfrn assembly fixed the issue completely.
