### ISSUE TITLE
Assigning alias from $GLOBALS to field causes assertion failure

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#173]
It happens only when the alias is returned from a separate function, see the test case:
```php
$globalFoo = true;
$hlp =& $globalFoo;

function foo() {
  return $GLOBALS['globalFoo'];
}

class A {
  protected $field;

  public function bar() {
    $this->field = foo();
  }
}

(new A)->bar();
```
Result:
```
FailFast:

   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at Pchp.Core.Operators.SetValue(PhpValue& target, PhpValue value)
   at A.bar() in C:\iolevel\peachpie-samples\console-application\main.php:line 247
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\iolevel\peachpie-samples\console-application\main.php:line 251
   at <Script>.Main(String[] args)
   ...
```

**Comment by jakubmisek** [comment]
fixed in https://github.com/peachpiecompiler/peachpie/commit/2a003d40d8f834c0d168b6550429e4581437f4f9
