### ISSUE TITLE
Method not found: 'Pchp.Core.Reflection.RoutineInfo Pchp.Core.Reflection.RoutineInfo.CreateUserRoutine(System.String, System.RuntimeMethodHandle)'.

### ISSUE THREAD

**Issue by gordon-matt** [peachpiecompiler/peachpie#191]
**EXCEPTION:** `The type initializer for '<Root>filemanager/include.utils_php' threw an exception.`
**INNER EXCEPTION:** `Method not found: 'Pchp.Core.Reflection.RoutineInfo Pchp.Core.Reflection.RoutineInfo.CreateUserRoutine(System.String, System.RuntimeMethodHandle)'.`
**STACK TRACE:**
```
   at <Root>filemanager/include.utils_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in D:\Source\GitHub\peachpie-responsive-file-manager\Website\filemanager\include\utils.php:line 98
   at <Root>filemanager/include.utils_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>filemanager.dialog_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in D:\Source\GitHub\peachpie-responsive-file-manager\Website\filemanager\dialog.php:line 26
   at <Root>filemanager.dialog_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.Web.PhpHandlerMiddleware.<>c__DisplayClass7_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**NOTE**: This is related to issue #185

**Comment by jakubmisek** [comment]
Just restore and rebuild. References were changed in the last update.

**Comment by gordon-matt** [comment]
@jakubmisek  Yes, I think I did do a `dotnet restore`, but I forgot to rebuild. Just did that now, and it caused a worse error - another **MSB3073** and this time the stack trace from the output window is as follows:

```
1>Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
1>   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
1>   at Pchp.CodeAnalysis.Symbols.CoreMethod.ResolveSymbol()
1>   at Pchp.CodeAnalysis.Symbols.CoreMethod.get_Symbol()
1>   at Pchp.CodeAnalysis.Symbols.SourceFunctionSymbol.EmitInit(PEModuleBuilder module)
1>   at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func)
1>   at Pchp.CodeAnalysis.SourceCompiler.EmitSynthesized()
1>   at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
1>   at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
1>   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
1>   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
1>   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
1>   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
1>   at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
1>C:\Users\Matt\.nuget\packages\peachpie.net.sdk\0.9.0-ci00853\build\Peachpie.NET.Core.Sdk.targets(154,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netstandard2.0\compile-php-args.rsp" exited with code -532462766.
1>Done building project "Website.msbuildproj" -- FAILED.
2>------ Build started: Project: Server, Configuration: Debug Any CPU ------
3>------ Build started: Project: WebApplication, Configuration: Debug Any CPU ------
3>CSC : error CS0006: Metadata file 'D:\Source\GitHub\peachpie-responsive-file-manager\Website\bin\Debug\netstandard2.0\ResponsiveFileManager.dll' could not be found
3>Done building project "WebApplication.csproj" -- FAILED.
2>CSC : error CS0006: Metadata file 'D:\Source\GitHub\peachpie-responsive-file-manager\Website\bin\Debug\netstandard2.0\ResponsiveFileManager.dll' could not be found
2>Done building project "Server.csproj" -- FAILED.
```

**Comment by jakubmisek** [comment]
Still running old nuget. I can tell since the stack trace contains methods that were removed in the new one.

**Comment by gordon-matt** [comment]
Hmm, not sure how that's possible.. as I even deleted the bin and obj folders to make sure. However, I will try again and see. If same problem, I will post here the `<PackageReference ...` values from my `.csproj` files.

**Comment by gordon-matt** [comment]
@jakubmisek Just tried again and exact same issue. I was very careful to delete all `bin` and `obj` folders, then run `dotnet restore` and rebuild. It just won't build. Here is my csproj:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>aspnet-WebApplication-0ED9D933-07CC-46A2-8DF4-30AF442E8C9F</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.2" PrivateAssets="All" />
    <PackageReference Include="Peachpie.NETCore.Web" Version="0.9.0-*" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Website\Website.msbuildproj" />
  </ItemGroup>

</Project>
```

and my `.msbuildproj` from the "Website" project:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <ProjectGuid>a271793f-72bf-429d-9ec8-83c03559cbd6</ProjectGuid>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>ResponsiveFileManager</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.php" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Peachpie.Compiler.Tools" Version="0.9.0-*" />
    <PackageReference Include="Peachpie.NET.Sdk" Version="0.9.0-*" PrivateAssets="Build" />
    <PackageReference Include="Peachpie.Library.Graphics" Version="0.9.0-*" />
    <PackageReference Include="Peachpie.Library.Network" Version="0.9.0-*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Media\Thumbs\" />
    <Folder Include="Media\Uploads\" />
  </ItemGroup>
</Project>
```

**Comment by jakubmisek** [comment]
Might be caused by the star in `0.9.0-*`. Try specify the version `0.9.0-CI00853`, and ensure NuGet packages are consolidated.

deleting bin and obj is not necessary
