### ISSUE TITLE
Error messages are possibly not helpful

### ISSUE THREAD

**Issue by glatzert** [peachpiecompiler/peachpie#216]
I gave peachpie a shot (probably I choose the orbital cannon 🛰) and tried to compile moodle.

The error message I got (somewhat expected) was not helpful:

```
Unhandled Exception: System.InvalidOperationException: Sequence contains more than one element
>      at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
>      at Pchp.CodeAnalysis.Symbols.PhpTypeSymbolExtensions.ResolveInstanceProperty(INamedTypeSymbol type, String name)
>      at Pchp.CodeAnalysis.FlowAnalysis.ExpressionAnalysis.VisitFieldRef(BoundFieldRef x)
>      at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func)
>      at Pchp.CodeAnalysis.FlowAnalysis.ExpressionAnalysis.VisitGlobalFunctionCall(BoundGlobalFunctionCall x, ConditionBranch branch)
>      at Pchp.CodeAnalysis.FlowAnalysis.ExpressionAnalysis.VisitAssign(BoundAssignEx x)
>      at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor.VisitCFGBlockStatements(BoundBlock x)
>      at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor.VisitCFGBlockInternal(BoundBlock x)
>      at Pchp.CodeAnalysis.FlowAnalysis.Worklist`1.Process(T block)
>      at Pchp.CodeAnalysis.FlowAnalysis.Worklist`1.DoAll(Boolean concurrent)
>      at Pchp.CodeAnalysis.SourceCompiler.BindAndAnalyze(PhpCompilation compilation)
>      at System.Threading.Tasks.Task`1.InnerInvoke()
>      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>      at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
>   --- End of stack trace from previous location where exception was thrown ---
>      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>      at Pchp.CodeAnalysis.PhpCompilation.<BindAndAnalyseTask>d__116.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---
>      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>      at Pchp.CodeAnalysis.PhpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
>      at Pchp.CodeAnalysis.PhpCompilation.GetDeclarationDiagnostics(CancellationToken cancellationToken)
>      at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 381
>      at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 295
>      at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
> C:\Users\glatzert\.nuget\packages\peachpie.net.sdk\0.9.0-ci00947\build\Peachpie.NET.Core.Sdk.targets(160,5): error MSB3073: Der Befehl "dotnet compile-php @obj\Debug\netstandard2.0\compile-php-args.rsp" wurde mit dem Code -532462766 beendet. [C:\Dev\GitHub\moodle\moodle.msbuildproj]
```

I think it would be an improvement, if peachpie would Point out, what the Problem with the PHP is and from which PHP file the Problem originates.

**Comment by jakubmisek** [comment]
Nice, that's a regular crash of the compiler, nothing wrong with your PHP. We'll take a look and fix it asap.

**Comment by jakubmisek** [comment]
@glatzert are we talking about this piece of code? https://download.moodle.org/download.php/moodle/moodle-latest.tgz

**Comment by glatzert** [comment]
I used the GitHub repository from moodle, but it's probably the same as the latest.tgz 👍

**Comment by glatzert** [comment]
I used this repository, https://github.com/moodle/moodle (Branch: MOODLE_35_STABLE),
with this msbuild-File:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.2</LangVersion>
    <ShortOpenTag>True</ShortOpenTag>
  </PropertyGroup>
 
  <ItemGroup>
    <Compile Include="**/*.php" />
  </ItemGroup>
 
  <ItemGroup>
    <DotNetCliToolReference Include="Peachpie.Compiler.Tools" Version="0.9.0-*" />
    <PackageReference Include="Peachpie.NET.Sdk" Version="0.9.0-*" PrivateAssets="Build" />
  </ItemGroup>
</Project>
```

**Comment by jakubmisek** [comment]
@glatzert thanks! for the latest version you can use build from this nuget feed https://www.myget.org/F/peachpie/api/v3/index.json

Also to build the project I suggest to exclude test files from the compilation (`<Compile Include="**/*.php" Exclude="**/phpunit/**" />`). The same issue will be with `php_user_filter` and `XMLWriter`.

**Comment by jakubmisek** [comment]
>note: requires implementation of:
- `SPLPriorityQueue`
- `XMLWriter`
- `XMLReader`
- `php_user_filter`

**Comment by glatzert** [comment]
Thanks a lot - now the errormessages are something, that can be acted upon 👍

**Comment by rakeshkgsg** [comment]
Hi, did u manage to get moodle compiled?
