### ISSUE TITLE
Null Ref Exception when compiling

### ISSUE THREAD

**Issue by Valks** [peachpiecompiler/peachpie#229]
When compiling I get the following error:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
     at Pchp.CodeAnalysis.Semantics.BoundPseudoConst.Emit(CodeGenerator cg)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to)
     at Pchp.CodeAnalysis.Symbols.SourceFieldSymbol.Pchp.CodeAnalysis.Symbols.IPhpPropertySymbol.EmitInit(CodeGenerator cg)
     at Pchp.CodeAnalysis.Symbols.SourceTypeSymbol.<>c__DisplayClass3_1.<EmitPhpCtors>b__0(ILBuilder il)
     at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
     at Pchp.CodeAnalysis.Symbols.SourceTypeSymbol.EmitPhpCtors(ImmutableArray`1 instancectors, PEModuleBuilder module, DiagnosticBag diagnostics)
     at Pchp.CodeAnalysis.Symbols.SourceTypeSymbol.SynthesizeInit(PEModuleBuilder module, DiagnosticBag diagnostics)
     at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func)
     at Pchp.CodeAnalysis.SourceCompiler.EmitSynthesized()
     at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1350
     at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1714
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 437
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 295
     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
C:\Users\User\.nuget\packages\peachpie.net.sdk\0.9.0-ci00981\build\Peachpie.NET.Core.Sdk.targets(160,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netstandard2.0\compile-php-args.rsp" exited with code -1073741819. [C:\repos\peachpie_site\src\Website\Website.msbuildproj]

Build FAILED.
```

**Comment by jakubmisek** [comment]
__FILE__, __DIR__, __CLASS__ was not handled in property initializers
