### ISSUE TITLE
How to analyse System.ArgumentException: Value does not fall within the expected range.

### ISSUE THREAD

**Issue by Remo** [peachpiecompiler/peachpie#235]
I know I'm aiming high, but I thought I'd try to run laravel on peachpie. With the rise of .net core I'm more tempted to switch to .net and if I could reuse some of my laravel code it wouldn't bother me.

I only tried to run the `artisan` script from laravel, this is what I get:

```
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 57.59 ms for C:\Work\php.net\project.msbuildproj.
  Restore completed in 17.9 ms for C:\Work\php.net\project.msbuildproj.
  PeachPie PHP Compiler version 0.9.0-CI01014
  
  Unhandled Exception: System.ArgumentException: Value does not fall within the expected range.
     at Pchp.CodeAnalysis.PhpCompilation.GetTypeFromTypeRef(TypeRef tref)
     at Pchp.CodeAnalysis.Symbols.SourceParameterSymbol.ResolveType()
     at Pchp.CodeAnalysis.Symbols.SourceParameterSymbol.get_Type()
     at Pchp.CodeAnalysis.Symbols.SignatureEqualityComparer.GetHashCode(IMethodSymbol obj)
     at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
     at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
     at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
     at Pchp.CodeAnalysis.Symbols.TypeSymbol.LookupMethods(String name)
     at Pchp.CodeAnalysis.FlowAnalysis.ExpressionAnalysis.VisitInstanceFunctionCall(BoundInstanceFunctionCall x)
     at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor.VisitCFGBlockStatements(BoundBlock x)
     at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor.VisitCFGBlockInternal(BoundBlock x)
     at Pchp.CodeAnalysis.FlowAnalysis.Worklist`1.Process(T block)
     at Pchp.CodeAnalysis.FlowAnalysis.Worklist`1.DoAll(Boolean concurrent)
     at Pchp.CodeAnalysis.SourceCompiler.BindAndAnalyze(PhpCompilation compilation)
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Pchp.CodeAnalysis.PhpCompilation.<BindAndAnalyseTask>d__116.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at Pchp.CodeAnalysis.PhpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.PhpCompilation.GetDeclarationDiagnostics(CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 381
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) in D:\Documents\Projects\Peachpie.Microsoft.CodeAnalysis\src\Compilers\Core\Portable\CommandLine\CommonCompiler.cs:line 295
     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
C:\Users\Remo\.nuget\packages\peachpie.net.sdk\0.9.0-ci01014\build\Peachpie.NET.Core.Sdk.targets(160,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netcoreapp2.0\compile-php-args.rsp" exited with code -532462766. [C:\Work\php.net\project.msbuildproj]

Build FAILED.

C:\Users\Remo\.nuget\packages\peachpie.net.sdk\0.9.0-ci01014\build\Peachpie.NET.Core.Sdk.targets(160,5): error MSB3073: The command "dotnet compile-php @obj\Debug\netcoreapp2.0\compile-php-args.rsp" exited with code -532462766. [C:\Work\php.net\project.msbuildproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:21.05
```

The callstack doesn't tell me much. Any hints about how I would have to analyse this?

**Comment by jakubmisek** [comment]
Thanks for the feedback and for trying laravel! 

The easiest way is to open `Peachpie.sln` in Visual Studio, open properties of `Peachpie.Compiler.Tools` project and set Additional Arguments: "@obj\Debug\netcoreapp2.0\compile-php-args.rsp" (the .rsp file was generated by previous run of your `dotnet build`)

Debug the project `Peachpie.Compiler.Tools`.

**Comment by Remo** [comment]
Thanks! Still don't get rid of the above exception, but this is causing a problem https://github.com/mockery/mockery/issues/897

**Comment by Remo** [comment]
It's pretty hard to get a picture of something like peachpie, tried to do what you said, but I always get `Peachpie.Runtime not found` and don't really understand the ReferenceManager. I guess I'll leave this up to the guys working with it regularly..
