### ISSUE TITLE
PDOStatement bindValue / Parameter 'key' not found in the collection

### ISSUE THREAD

**Issue by NoahTarr** [peachpiecompiler/peachpie#243]
$sql = $db->prepare("SELECT * FROM $tableName WHERE UPPER($colName) LIKE UPPER(:key)");
$sql->bindValue(':key', '%' . $key . '%', PDO::PARAM_STR);
$sql->execute();

Breaks at execute() with exception:
Exception has occurred: CLR/System.ArgumentException
An unhandled exception of type 'System.ArgumentException' occurred in MySqlConnector.dll: 'Parameter 'key' not found in the collection'
   at MySql.Data.MySqlClient.MySqlParameterCollection.GetParameter(String parameterName) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlParameterCollection.cs:line 85
   at Peachpie.Library.PDO.PDOStatement.bindValue(PhpValue parameter, PhpValue value, Int32 data_type)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid5[T0,T1,T2,T3,T4](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at <Root>assets/php.functions_php.call_data_from_db(Context <ctx>, PhpValue tableName, PhpValue column, PhpValue key) in Z:\NoahTarr-Intern\Calsoft Website PeachPie Integration\assets\php\functions.php:line 52
   at <Root>assets/php.calibrationSoftware_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in Z:\NoahTarr-Intern\Calsoft Website PeachPie Integration\assets\php\calibrationSoftware.php:line 6
   at <Script>.Main(String[] args)

**Comment by jakubmisek** [comment]
related to https://github.com/peachpiecompiler/peachpie/issues/234

**Comment by jan-pavlovsky** [comment]
Thanks for the info, we are working on that..

**Comment by jan-pavlovsky** [comment]
Should be fixed now with PR #245

**Comment by jakubmisek** [comment]
closed for inactivity
