### ISSUE TITLE
compiler crash - Spaceship operator not implemented

### ISSUE THREAD

**Issue by cruelbob** [peachpiecompiler/peachpie#257]
```
$ dotnet build
Microsoft (R) Build Engine версии 15.7.179.6572 для .NET Core
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Восстановление завершено в 57,1 ms для path/project.msbuildproj.
  Восстановление завершено в 15,43 ms для path/project.msbuildproj.
  PeachPie PHP Compiler version 0.9.0-CI01042
  
  Unhandled Exception: System.InvalidOperationException: This program location is thought to be unreachable.
     at Pchp.CodeAnalysis.FlowAnalysis.ExpressionAnalysis.ResolveBinaryEx(BoundBinaryEx x, ConditionBranch branch)
     at Pchp.CodeAnalysis.FlowAnalysis.ExpressionAnalysis.Visit(BoundBinaryEx x, ConditionBranch branch)
     at Pchp.CodeAnalysis.FlowAnalysis.ExpressionAnalysis.VisitAssign(BoundAssignEx x)
     at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor.VisitCFGBlockStatements(BoundBlock x)
     at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor.VisitCFGBlockInternal(BoundBlock x)
     at Pchp.CodeAnalysis.FlowAnalysis.Worklist`1.Process(T block)
     at Pchp.CodeAnalysis.FlowAnalysis.Worklist`1.DoAll(Boolean concurrent)
     at Pchp.CodeAnalysis.SourceCompiler.BindAndAnalyze(PhpCompilation compilation)
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
  --- End of stack trace from previous location where exception was thrown ---
     at Pchp.CodeAnalysis.PhpCompilation.BindAndAnalyseTask()
     at Pchp.CodeAnalysis.PhpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.PhpCompilation.GetDeclarationDiagnostics(CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
~/.nuget/packages/peachpie.net.sdk/0.9.0-ci01042/build/Peachpie.NET.Core.Sdk.targets(160,5): error MSB3073: выход из команды "dotnet compile-php @obj/Debug/netcoreapp2.0/compile-php-args.rsp" с кодом 134. [path/project.msbuildproj]
```
project.msbuildproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
 
  <ItemGroup>
    <Compile Include="**/*.php" />
  </ItemGroup>
 
  <ItemGroup>
    <DotNetCliToolReference Include="Peachpie.Compiler.Tools" Version="0.9.0-*" />
    <PackageReference Include="Peachpie.NET.Sdk" Version="0.9.0-*" PrivateAssets="Build" />
  </ItemGroup>
</Project>
```

**Comment by jakubmisek** [comment]
Thanks! it would help to see the PHP code causing this - we're probably not handling this binary expression yet.

**Comment by jakubmisek** [comment]
`0.9.0-CI01065` on our NuGet feed https://www.myget.org/F/peachpie/api/v3/index.json gets you more detailed info about the error, please try that version; you should see "unexpected value xxx" instead of "InvalidOperationException"

**Comment by cruelbob** [comment]
```

**Comment by jakubmisek** [comment]
@cruelbob thanks!

**Comment by jakubmisek** [comment]
implemented in 392fc3ff977542338855094c11ff180d1b2abf79

**Comment by cruelbob** [comment]
confirm fix

**Comment by jakubmisek** [comment]
thanks for checking
