### ISSUE TITLE
throws System.InvalidProgramException when using trycatch block

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#260]
```
发生异常: CLR/System.InvalidProgramException
Exception thrown: 'System.InvalidProgramException' in NULASpider.dll: 'Common Language Runtime detected an invalid program.'
   at nulastudio.Spider.Spider.find_urls(PhpValue content, PhpValue request, PhpValue response) in O:\project\NULASpider\NULASpider\src\Spider.php:line 315
   at nulastudio.Spider.Spider.find_list_url(PhpValue content, PhpValue request, PhpValue response) in O:\project\NULASpider\NULASpider\src\Spider.php:line 262
```

here's my code
```php
    private function find_urls($content, $request, $response)
    {
        $urls = [];
        try {
            $document = new \HtmlAgilityPack\HtmlDocument();
            $document->LoadHtml($content);
            $nodes = $document->DocumentNode->SelectNodes("//a[@href]");
            foreach ($nodes as $node) {
                // $attrs  = new \Pchp\Core\PhpArray($node->Attributes);
                // $urls[] = $attrs["href"]->Value;
                foreach ($node->Attributes as $attr) {
                    if ($attr && $attr->Name === 'href') {
                        $urls[] = $attr->Value;
                    }
                }
                // $urls[] = $node->Attributes["href"]->Value;
            }
        } catch (\Exception $e) {
        } finally {
            return $urls;
        }
        ;
    }
```
it runs fine if remove the trycatch block

**Comment by jakubmisek** [comment]
minimal test case:
```php
function find_urls()
{
    try {
        
    }
    finally
    {
        return 1;
    }
}
```

**Comment by liesauer** [comment]
@jakubmisek last night it works! but this morning it crash again with nothing changed. i can not figer out why it happend again

**Comment by jakubmisek** [comment]
there are still some issues with try/finally. Will be fixed.

**Comment by jakubmisek** [comment]
we'll probably report jump from `finally` as unsupported. `return` should be outside of the `finally` block

**Comment by liesauer** [comment]
@jakubmisek that is fine!
