### ISSUE TITLE
compile-php error

### ISSUE THREAD

**Issue by cruelbob** [peachpiecompiler/peachpie#272]
compile-php exited with code 134 without exceptions:
```
"~/projects/peachpie_test1/peachpie_test1.msbuildproj" (build target) (1) ->
(CoreCompile target) ->
  ~/.nuget/packages/peachpie.net.sdk/0.9.0-ci01101/build/Peachpie.NET.Core.Sdk.targets(160,5): error MSB3073: The command "dotnet compile-php @obj/Debug/netcoreapp2.0/compile-php-args.rsp" exited with code 134. [~/projects/peachpie_test1/peachpie_test1.msbuildproj]
```

**Comment by jakubmisek** [comment]
Do you see an exception somewhere in the middle of the log output?

**Comment by cruelbob** [comment]
Found exception. It isn't showed from "dotnet run" command. But it is visible from "dotnet build".
```
Unhandled Exception: System.NotImplementedException: (ensure) STORE PhpValue[] not implemented at ~/peachpie_test1/app/Model/PlayerStorage.php(244, 8)
     at Pchp.CodeAnalysis.Semantics.BoundArrayItemEx.Pchp.CodeAnalysis.CodeGen.IBoundReference.EmitStorePrepare(CodeGenerator cg, InstanceCacheHolder instanceOpt)
     at Pchp.CodeAnalysis.Semantics.BoundAssignEx.Emit(CodeGenerator cg)
     at Pchp.CodeAnalysis.Semantics.BoundExpressionStatement.Emit(CodeGenerator cg)
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Emit(CodeGenerator cg)
     at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Generate(CodeGenerator cg)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
     at Pchp.CodeAnalysis.Symbols.SourceRoutineSymbol.Generate(CodeGenerator cg)
     at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
     at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBody(SourceRoutineSymbol routine)
     at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func)
     at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBodies()
     at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
```
lines 241-245:
```

**Comment by jakubmisek** [comment]
@cruelbob thanks!

**Comment by jakubmisek** [comment]
A test case for a reference:
```php
class X {
    function bar() { return []; } // : PhpValue
}

$x = new X;
$x->bar()[1] = 2; // System.NotImplementedException: '(ensure) STORE PhpValue[]
```

**Comment by jakubmisek** [comment]
we'll write some docs about it .. for now:

The simplest way is to build the solution, notice the build creates bunch of nuget packages in `/.nugs` folder (subject of change).

Then use script at `build` directory and call it
```shell
.\update-cache.ps1 0.9.0
```
This installs the packages into your local repository.

Then within the PHP project, reference the development packages `0.9.0-dev` instead of `0.9.0-*`.
