### ISSUE TITLE
Missing file info (<unknown>)

### ISSUE THREAD

**Issue by cruelbob** [peachpiecompiler/peachpie#273]
How can I get filename and line which cause this exception?
```
Unhandled Exception: System.NotImplementedException: (long)DateTime not implemented at <unknown>
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvertToLong(TypeSymbol from, TypeRefMask fromHint)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(TypeSymbol from, TypeRefMask fromHint, TypeSymbol to)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitLoadArgument(ParameterSymbol targetp, BoundExpression expr, List`1 writebacks)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitCall(ILOpCode code, MethodSymbol method, BoundExpression thisExpr, ImmutableArray`1 arguments, IBoundTypeRef staticType)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitForwardCall(MethodSymbol target, MethodSymbol thismethod, IPlace thisPlaceExplicit, Boolean callvirt)
     at Pchp.CodeAnalysis.CodeGen.GhostMethodBuilder.<>c__DisplayClass1_0.<GenerateGhostBody>b__0(ILBuilder il)
     at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
     at Pchp.CodeAnalysis.CodeGen.GhostMethodBuilder.GenerateGhostBody(PEModuleBuilder module, DiagnosticBag diagnostic, MethodSymbol method, SynthesizedMethodSymbol ghost)
     at Pchp.CodeAnalysis.CodeGen.GhostMethodBuilder.CreateGhostOverload(MethodSymbol method, NamedTypeSymbol containingtype, PEModuleBuilder module, DiagnosticBag diagnostic, TypeSymbol ghostreturn, IEnumerable`1 ghostparams, Boolean phphidden, MethodSymbol explicitOverride)
     at Pchp.CodeAnalysis.Symbols.SourceTypeSymbol.FinalizeMethodTable(PEModuleBuilder module, DiagnosticBag diagnostics)
     at Pchp.CodeAnalysis.SourceCompiler.<EmitSynthesized>b__25_1(SourceTypeSymbol t)
     at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func)
     at Pchp.CodeAnalysis.SourceCompiler.WalkTypes(Action`1 action, Boolean allowParallel)
     at Pchp.CodeAnalysis.SourceCompiler.EmitSynthesized()
     at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.CommandLine.PhpCompilerDriver.Run(CommandLineParser parser, String responseFile, String[] args, String clientDirectory, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories, IAnalyzerAssemblyLoader analyzerLoader, TextWriter output)
     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
```

**Comment by jakubmisek** [comment]
Actually this one is caused by implementing an override or an interface where base declaration accepts a parameter of type `long` (integer) and the override has the parameter of type `DateTime`. The conversion is *generated* in order to create valid CLR assembly so the exception does not correspond to exact line in your code. .. we have to add more information.

**Comment by jakubmisek** [comment]
https://github.com/peachpiecompiler/peachpie/commit/b26a0c72dc421eb2edbb0729fb23e15b6278818f adds more detailed message which should reveal the exact location of that unimplemented feature.

**Comment by cruelbob** [comment]
thx
