### ISSUE TITLE
parent construct error

### ISSUE THREAD

**Issue by cruelbob** [peachpiecompiler/peachpie#274]
test.php:
```php
<?php
class Foo
{
    public function __construct(\DateTime $d)
    {
    }
}

class Bar extends Foo
{
    public function __construct(int $i, \DateTime $d)
    {
        parent::__construct($d);
    }
}
```
compiler output:
```
Unhandled Exception: System.NotImplementedException: (long)Pchp.Library.DateTime.DateTime not implemented at ~/projects/peachpie_test/test.php in Bar::__construct
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvertToLong(TypeSymbol from, TypeRefMask fromHint)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(TypeSymbol from, TypeRefMask fromHint, TypeSymbol to)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitLoadArgument(ParameterSymbol targetp, BoundExpression expr, List`1 writebacks)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitCall(ILOpCode code, MethodSymbol method, BoundExpression thisExpr, ImmutableArray`1 arguments, IBoundTypeRef staticType)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitForwardCall(MethodSymbol target, MethodSymbol thismethod, IPlace thisPlaceExplicit, Boolean callvirt)
     at Pchp.CodeAnalysis.CodeGen.GhostMethodBuilder.<>c__DisplayClass1_0.<GenerateGhostBody>b__0(ILBuilder il)
     at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
     at Pchp.CodeAnalysis.CodeGen.GhostMethodBuilder.GenerateGhostBody(PEModuleBuilder module, DiagnosticBag diagnostic, MethodSymbol method, SynthesizedMethodSymbol ghost)
     at Pchp.CodeAnalysis.CodeGen.GhostMethodBuilder.CreateGhostOverload(MethodSymbol method, NamedTypeSymbol containingtype, PEModuleBuilder module, DiagnosticBag diagnostic, TypeSymbol ghostreturn, IEnumerable`1 ghostparams, Boolean phphidden, MethodSymbol explicitOverride)
     at Pchp.CodeAnalysis.Symbols.SourceTypeSymbol.FinalizeMethodTable(PEModuleBuilder module, DiagnosticBag diagnostics)
     at Pchp.CodeAnalysis.SourceCompiler.<EmitSynthesized>b__25_1(SourceTypeSymbol t)
     at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func)
     at Pchp.CodeAnalysis.SourceCompiler.WalkTypes(Action`1 action, Boolean allowParallel)
     at Pchp.CodeAnalysis.SourceCompiler.EmitSynthesized()
     at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.PhpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.CommandLine.PhpCompilerDriver.Run(CommandLineParser parser, String responseFile, String[] args, String clientDirectory, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories, IAnalyzerAssemblyLoader analyzerLoader, TextWriter output)
     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)

```

**Comment by cruelbob** [comment]
@jakubmisek hello! Would it be hard to fix this issue?

**Comment by jakubmisek** [comment]
@cruelbob it is not hard, but there are more possible approaches. Will be fixed within a day. Thanks!

**Comment by jakubmisek** [comment]
It was fixed by treating __construct as non-virtual (so compiler does not generate the "override" stub). Other PHP functions are fine because their signatures have to match.

**Comment by cruelbob** [comment]
Thanks!
