### ISSUE TITLE
Attempt to access the method failed when creating Carbon\Carbon

### ISSUE THREAD

**Issue by Remo** [peachpiecompiler/peachpie#290]
I'm getting this error:
```
Unhandled Exception: System.MethodAccessException: Attempt to access the method failed.
   at Pchp.Core.Reflection.PhpTypeInfo.<>c.<.cctor>b__61_0(Context ctx, PhpValue[] _)
   at Pchp.Core.Context.Create[T](RuntimeTypeHandle caller, PhpValue[] arguments)
   at Illuminate.Database.Eloquent.Concerns.HasTimestamps`1.freshTimestamp() in C:\work\eloquent-peachpie\vendor\illuminate\database\Eloquent\Concerns\HasTimestamps.php:line 84
   at Illuminate.Database.Eloquent.Model.freshTimestamp()
   at CallSite.Target(Closure , CallSite , Object , Context )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Illuminate.Database.Eloquent.Concerns.HasTimestamps`1.updateTimestamps() in C:\work\eloquent-peachpie\vendor\illuminate\database\Eloquent\Concerns\HasTimestamps.php:line 39
   at Illuminate.Database.Eloquent.Model.updateTimestamps()
   at Illuminate.Database.Eloquent.Model.performInsert(Builder query) in C:\work\eloquent-peachpie\vendor\illuminate\database\Eloquent\Model.php:line 778
   at Illuminate.Database.Eloquent.Model.save(PhpArray options) in C:\work\eloquent-peachpie\vendor\illuminate\database\Eloquent\Model.php:line 649
   at Illuminate.Database.Eloquent.Model.save()
   at CallSite.Target(Closure , CallSite , PhpValue , Context , CallerTypeParam )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at <Root>.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\work\eloquent-peachpie\index.php:line 40
   at <Script>.Main(String[] args)
```

This is how you can reproduce this:

composer.json:
```
{
    "require": {
        "illuminate/database": "^5.7"
    }
}
```

index.php:
```
<?php
require 'vendor/autoload.php';

use Illuminate\Database\Capsule\Manager as Capsule;

$capsule = new Capsule;

$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => 'localhost',
    'database'  => 'peachpie',
    'username'  => 'root',
    'password'  => '',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => '',
]);

// Make this Capsule instance available globally via static methods... (optional)
$capsule->setAsGlobal();

// Setup the Eloquent ORM... (optional; unless you've used setEventDispatcher())
$capsule->bootEloquent();

Capsule::schema()->dropIfExists('users');

Capsule::schema()->create('users', function($table)
{
    $table->increments('id');
    $table->string('email')->unique();
    $table->timestamps();
});

class User extends Illuminate\Database\Eloquent\Model {}

$user = new User();
$user->email = 'remo.laubacher@ortic.com';
$user->save();

$users = User::all();
foreach ($users as $user) {
    echo $user->email . "\n";
}
```

eloquent-peachpie.msbuildproj:
```
<Project Sdk="Peachpie.NET.Sdk/0.9.10">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <StartupObject>index.php</StartupObject>
    <Description>Simpliest PHP project for .NET Core, a console application.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.php" Exclude="**/phpunit**;**/Tests/**;**/Seeds/**;**/Testing/**;**/Migrations/**;**/TranslatorPass.php;**/TranslationExtractorPass.php;**/TranslationDataCollector.php;**/TranslationDumperPass.php;**/FactoryMakeCommand.php;**/XliffLintCommand.php" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Peachpie.Library.MySql" Version="0.9.11" />
    <PackageReference Include="Peachpie.Library.PDO" Version="0.9.11" />
    <PackageReference Include="Peachpie.Library.PDO.MySQL" Version="0.9.11" />
  </ItemGroup>
  
</Project>
```

I wish I could be of more help, but my knowledge about roselyn and those things is almost at zero.. I hope this error report still helps you.

**Comment by jakubmisek** [comment]
It seams the compiler did not emit `.ctor` for the class `Carbon`

**Comment by jakubmisek** [comment]
great test case, thanks!

the issue should be fixed in https://github.com/peachpiecompiler/peachpie/commit/6464c4c65d854f79e741dff9f1631e6a5a01ffda and https://github.com/peachpiecompiler/peachpie/commit/bfbdb8eb094b9fccd092b8a4d3833c41512e101c

**Comment by jakubmisek** [comment]
You can either build from sources, or wait for a preview build. Recommending to alter your msbuildproj:
```xml
<Project Sdk="Peachpie.NET.Sdk/0.9.11">

  ...

  <ItemGroup>
    <PackageReference Include="Peachpie.Library.PDO.MySQL" Version="$(PeachpieVersion)" />
  </ItemGroup>
  
</Project>
```

- the Sdk version should be the same as versions of referenced libraries
- `$(PeachpieVersion)` is set by the Sdk to 0.9.11

**Comment by Remo** [comment]
Awesome, thanks! One more piece working to get laravel running.
