### ISSUE TITLE
NullReferenceException during compilation

### ISSUE THREAD

**Issue by profMagija** [peachpiecompiler/peachpie#298]
Trying to compile the following code generates a NullReferenceException:

```php
<?php

class C {
	const A = 1 | 1 << 1;
}
```

Stacktrace (from running a test):

```
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.IsLongOnly(TypeRefMask tmask) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/CodeGen/CodeGenerator.TypeRef.cs:line 33
   at Pchp.CodeAnalysis.Semantics.BoundBinaryEx.EmitBitOr(CodeGenerator cg, BoundExpression left, BoundExpression right) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/CodeGen/Graph/BoundExpression.cs:line 569
   at Pchp.CodeAnalysis.Semantics.BoundBinaryEx.Emit(CodeGenerator cg) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/CodeGen/Graph/BoundExpression.cs:line 113
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/CodeGen/CodeGenerator.Convert.cs:line 1253
   at Pchp.CodeAnalysis.Symbols.SourceFieldSymbol.Pchp.CodeAnalysis.Symbols.IPhpPropertySymbol.EmitInit(CodeGenerator cg) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/CodeGen/Symbols/SourceFieldSymbol.cs:line 33
   at Pchp.CodeAnalysis.Symbols.SynthesizedStaticFieldsHolder.<>c__DisplayClass0_0.<EmitCtors>b__0(ILBuilder il) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/CodeGen/Symbols/SynthesizedStaticFieldsHolder.cs:line 45
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/CodeGen/MethodGenerator.cs:line 99
   at Pchp.CodeAnalysis.Symbols.SynthesizedStaticFieldsHolder.EmitCtors(PEModuleBuilder module) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/CodeGen/Symbols/SynthesizedStaticFieldsHolder.cs:line 25
   at Pchp.CodeAnalysis.Symbols.SourceTypeSymbol.SynthesizeInit(PEModuleBuilder module, DiagnosticBag diagnostics) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/CodeGen/Symbols/SourceTypeSymbol.cs:line 23
   at Pchp.CodeAnalysis.SourceCompiler.<EmitSynthesized>b__26_2(SourceTypeSymbol t) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/Compilation/SourceCompiler.cs:line 252
   at Pchp.CodeAnalysis.EnumeratorExtension.ForEach[T](IEnumerable`1 enumerable, Action`1 func) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/Utilities/EnumeratorExtension.cs:line 63
   at Pchp.CodeAnalysis.SourceCompiler.WalkTypes(Action`1 action, Boolean allowParallel) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/Compilation/SourceCompiler.cs:line 83
   at Pchp.CodeAnalysis.SourceCompiler.EmitSynthesized() in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/Compilation/SourceCompiler.cs:line 252
   at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/Compilation/SourceCompiler.cs:line 377
   at Pchp.CodeAnalysis.PhpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in /home/prof/RiderProjects/peachpie/src/Peachpie.CodeAnalysis/Compilation/PhpCompilation.cs:line 884
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)
   at Peachpie.Library.Scripting.Script.Create(ScriptOptions options, String code, PhpCompilationFactory builder, IEnumerable`1 previousSubmissions) in /home/prof/RiderProjects/peachpie/src/Peachpie.Library.Scripting/Context.Script.cs:line 239
   at Peachpie.Library.Scripting.ScriptingProvider.Pchp.Core.Context.IScriptingProvider.CreateScript(ScriptOptions options, String code) in /home/prof/RiderProjects/peachpie/src/Peachpie.Library.Scripting/Context.ScriptingProvider.cs:line 51
   at ScriptsTest.ScriptsTest.CompileAndRun(String path) in /home/prof/RiderProjects/peachpie/src/Tests/Peachpie.ScriptTests/ScriptsTest.cs:line 70
   at ScriptsTest.ScriptsTest.ScriptRunTest(String dir, String fname) in /home/prof/RiderProjects/peachpie/src/Tests/Peachpie.ScriptTests/ScriptsTest.cs:line 35
```

Same error goes for other bitwise operations operations.

**Comment by jakubmisek** [comment]
thanks for the issue and the PR.

This is an issue in field/consts initializers, where the value is analyzed but it is missing the function context (`TypeRefContext`). Will be merged & fixed.
