### ISSUE TITLE
RecursiveDirectoryIterator not implemented

### ISSUE THREAD

**Issue by Remo** [peachpiecompiler/peachpie#313]
I tried to get box/spout running, but it doesn't seem to work.

Here's my code.:

```composer require box/spout``` 

And:

```php
<?php
use Box\Spout\Writer\WriterFactory;
use Box\Spout\Common\Type;

require 'vendor/autoload.php';

$writer = WriterFactory::create(Type::XLSX); // for XLSX files
$writer->openToFile("test.xlsx");
$writer->addRow([1, 'test']);
$writer->close();
```

Shows me this:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Pchp.Core.Reflection.TypeMembersUtils.GetDeclaredConstant(PhpTypeInfo tinfo, String name)
   at Pchp.Core.Dynamic.GetFieldBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Box.Spout.Writer.Common.Helper.ZipHelper.addFolderToArchive(PhpValue folderPath, PhpValue existingFileMode) in C:\work\peachpie-spout\vendor\box\spout\src\Spout\Writer\Common\Helper\ZipHelper.php:line 152
   at Box.Spout.Writer.XLSX.Helper.FileSystemHelper.zipRootFolderAndCopyToStream(PhpValue streamPointer) in C:\work\peachpie-spout\vendor\box\spout\src\Spout\Writer\XLSX\Helper\FileSystemHelper.php:line 365
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at Box.Spout.Writer.XLSX.Internal.Workbook.close(PhpValue finalFilePointer) in C:\work\peachpie-spout\vendor\box\spout\src\Spout\Writer\XLSX\Internal\Workbook.php:line 115
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at Box.Spout.Writer.XLSX.Writer.closeWriter() in C:\work\peachpie-spout\vendor\box\spout\src\Spout\Writer\XLSX\Writer.php:line 129
   at Box.Spout.Writer.AbstractWriter.close() in C:\work\peachpie-spout\vendor\box\spout\src\Spout\Writer\AbstractWriter.php:line 357
   at CallSite.Target(Closure , CallSite , PhpValue , Context , CallerTypeParam )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at <Root>.program_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\work\peachpie-spout\program.php:line 10
   at <Script>.Main(String[] args)
```

There are also some warnings, but those I don't care about:

```
C:\work\peachpie-spout\vendor\box\spout\src\Spout\Common\Escaper\ODS.php(35,13): warning PHP5011: Unreachable code detected [C:\work\peachpie-spout\peachpie-spout.msbuildproj]
C:\work\peachpie-spout\vendor\box\spout\src\Spout\Writer\Common\Helper\ZipHelper.php(152,60): warning PHP5008: Class 'RecursiveDirectoryIterator' not found [C:\work\peachpie-spout\peachpie-spout.msbuildproj]
C:\work\peachpie-spout\vendor\box\spout\src\Spout\Common\Helper\FileSystemHelper.php(101,17): warning PHP5008: Class 'RecursiveDirectoryIterator' not found [C:\work\peachpie-spout\peachpie-spout.msbuildproj]
C:\work\peachpie-spout\vendor\box\spout\src\Spout\Writer\Common\Helper\ZipHelper.php(152,101): warning PHP5008: Class 'RecursiveDirectoryIterator' not found [C:\work\peachpie-spout\peachpie-spout.msbuildproj]
C:\work\peachpie-spout\vendor\box\spout\src\Spout\Common\Helper\FileSystemHelper.php(101,58): warning PHP5008: Class 'RecursiveDirectoryIterator' not found [C:\work\peachpie-spout\peachpie-spout.msbuildproj]
C:\work\peachpie-spout\vendor\composer\ClassLoader.php(345,21): warning PHP5006: Call to undefined function: 'Composer\Autoload\apcu_fetch' [C:\work\peachpie-spout\peachpie-spout.msbuildproj]
C:\work\peachpie-spout\vendor\composer\autoload_real.php(26,133): warning PHP5006: Call to undefined function: 'zend_loader_file_encoded' [C:\work\peachpie-spout\peachpie-spout.msbuildproj]
C:\work\peachpie-spout\vendor\composer\ClassLoader.php(345,58): warning PHP5007: Undefined variable: $hit [C:\work\peachpie-spout\peachpie-spout.msbuildproj]
C:\work\peachpie-spout\vendor\composer\ClassLoader.php(359,13): warning PHP5006: Call to undefined function: 'Composer\Autoload\apcu_add' [C:\work\peachpie-spout\peachpie-spout.msbuildproj]
```

**Comment by Remo** [comment]
Sorry, I guess the warnings matter, right after I posted this I saw that `RecursiveDirectoryIterator` isn't implemented. Guess I'm out of luck with box/spout

**Comment by bfistein** [comment]
Hi @Remo, you're right. This has not been implemented yet - wanna give it a shot? :)

**Comment by Remo** [comment]
not really my strength, never done any work with roselyn. Would take me way more time than I have.

**Comment by bfistein** [comment]
You don't need any knowledge of Roslyn. See [this iterator](https://github.com/peachpiecompiler/peachpie/blob/9db294068f3112cd071b1b7d209c5d76d0e40d93/src/Peachpie.Library/SPL/Iterators.cs) for reference. But no worries if you don't feel like doing it, we'll definitely implement this, I just can't give you an ETA.

**Comment by Remo** [comment]
well, I don't have a project where I need this, I'm just keeping an eye on peachpie because I'd like to move a few things to .net core.

**Comment by bfistein** [comment]
That's great to hear. We appreciate the issues and will do our best to address them.

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/31d546f94acf7857b9355bfd1abdd8143e1c0822
