### ISSUE TITLE
Wordpress 5.0 support

### ISSUE THREAD

**Issue by dvdobrovolskiy** [peachpiecompiler/peachpie#332]
Hi folks

Just compiled and launched wordpress 5.0 under peachpie. Mostly all good. Thanks for your work.

Website and all admin interface (all sections) works fine. One problem

Exception then editing post or page
This link for ex
http://mydomain.com:5004/wp-admin/post.php?post=2&action=edit

`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://mydomain.com:5004/wp-admin/post.php?post=2&action=edit
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLIU4825PJ6M", Request id "0HLIU4825PJ6M:00000009": An unhandled exception was thrown by the application.
System.InvalidCastException: Specified cast is not valid.
   at Pchp.Core.PhpValue.TypeTable.GetArray(PhpValue& me)
   at WP_REST_Server.get_data_for_route(PhpValue route, PhpValue callbacks, PhpValue context)
   at WP_REST_Server.get_data_for_routes(PhpValue routes, PhpValue context) in C:\Users\D\Downloads\wpdotnet-sdk-master\wordpress\wp-includes\rest-api\class-wp-rest-server.php:line 1106
   at WP_REST_Server.get_index(PhpValue request) in C:\Users\D\Downloads\wpdotnet-sdk-master\wordpress\wp-includes\rest-api\class-wp-rest-server.php:line 1019
   at <>.get_index(WP_REST_Server , PhpValue )
   at get_index#1(Closure , Context , Object , PhpValue[] )
   at WP_REST_Server.dispatch(PhpValue request)
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at <Root>wp-includes.rest-api_php.rest_do_request(Context <ctx>, PhpValue request)
   at <Root>wp-includes.rest-api_php.rest_preload_api_request(Context <ctx>, PhpValue memo, PhpValue path)
   at rest_preload_api_request#1(Closure , Context , PhpValue[] )
   at Pchp.Library.Arrays.array_reduce(Context ctx, PhpArray array, IPhpCallable function, PhpValue initialValue)
   at <Root>wp-admin.edit-form-blocks_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>wp-admin.edit-form-blocks_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>wp-admin.post_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.<>c__DisplayClass7_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
`

Update
Fails here
..\wpdotnet-sdk-master\wordpress\wp-includes\rest-api\class-wp-rest-server.php
1172

$data['methods'] = array_merge( $data['methods'], array_keys( $callback['methods'] ) );

**Comment by jakubmisek** [comment]
Hi! Great you're trying latest wp! This is fixed with the latest commit https://github.com/peachpiecompiler/peachpie/commit/b174a215f476ee5aec6b1b4a3e6b0e3ff14435de 

`$callback` is a string so the condition above (line 1168) should not pass.

**Comment by dvdobrovolskiy** [comment]
Perfect! many thanks
