### ISSUE TITLE
Compile Error: Conversion from 'PhpResource' to 'SocketOptions'. not implemented

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#366]
While trying to compile (latest version of) vendor lib react/socket with PeachPie PHP Compiler version 0.9.35 the following exception is thrown:

  Unhandled Exception: System.AggregateException: One or more errors occurred. (Conversion from 'PhpResource' to 'SocketOptions'. not implemented at C:\dotnetvendor\vendor\react\socket\src\TcpServer.php(155, 8)) ---> System.NotImplementedException: Conversion from 'PhpResource' to 'SocketOptions'. not implemented at C:\dotnetvendor\vendor\react\socket\src\TcpServer.php(155, 8)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(TypeSymbol from, TypeRefMask fromHint, TypeSymbol to) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Convert.cs:line 593
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Convert.cs:line 581
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitCall(ILOpCode code, MethodSymbol method, BoundExpression thisExpr, ImmutableArray`1 arguments, BoundTypeRef staticType) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Emit.cs:line 1715
     at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.EmitDirectCall(CodeGenerator cg, ILOpCode opcode, MethodSymbol method, BoundTypeRef staticType) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundExpression.cs:line 2489
     at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.Emit(CodeGenerator cg) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundExpression.cs:line 2468
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitSpecialize(BoundExpression expr) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Emit.cs:line 315
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitWithDisabledErrorReporting(BoundExpression expr) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Emit.cs:line 2542
     at Pchp.CodeAnalysis.Semantics.BoundUnaryEx.Emit(CodeGenerator cg) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundExpression.cs:line 2077
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitSpecialize(BoundExpression expr) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Emit.cs:line 315
     at Pchp.CodeAnalysis.Semantics.BoundCopyValue.Emit(CodeGenerator cg) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundExpression.cs:line 2245
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitSpecialize(BoundExpression expr) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.Emit.cs:line 315
     at Pchp.CodeAnalysis.Semantics.BoundAssignEx.Emit(CodeGenerator cg) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundExpression.cs:line 3213
     at Pchp.CodeAnalysis.Semantics.BoundExpressionStatement.Emit(CodeGenerator cg) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundStatement.cs:line 46
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Emit(CodeGenerator cg) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundBlock.cs:line 24
     at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Generate(CodeGenerator cg) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundEdge.cs:line 92
     at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Generate(CodeGenerator cg) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\Graph\BoundEdge.cs:line 92
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\CodeGenerator.cs:line 477
     at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CodeGen\MethodGenerator.cs:line 118
     at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBody(SourceRoutineSymbol routine) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\Compilation\SourceCompiler.cs:line 298
     at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica.Execute()
     --- End of inner exception stack trace ---
     at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
     at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
     at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
     at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBodies() in C:\a\e9a603f\src\Peachpie.CodeAnalysis\Compilation\SourceCompiler.cs:line 273
     at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\Compilation\SourceCompiler.cs:line 443
     at Pchp.CodeAnalysis.PhpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\Compilation\PhpCompilation.cs:line 906
     at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.CommandLine.PhpCompilerDriver.Run(CommandLineParser parser, String responseFile, String[] args, String clientDirectory, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories, IAnalyzerAssemblyLoader analyzerLoader, TextWriter output) in C:\a\e9a603f\src\Peachpie.CodeAnalysis\CommandLine\PhpCompilerDriver.cs:line 20
     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args) in C:\a\e9a603f\src\Peachpie.Compiler.Tools\Program.cs:line 21

**Comment by jakubmisek** [comment]
thanks, `stream_socket_server` has a wrong signature, expecting one more argument of a different type. Fixed
