### ISSUE TITLE
The method or operation is not implemented. ---> System.NotImplementedException: The method or operation is not implemented. at Pchp.CodeAnalysis.CodeGen.CodeGenerator.LoadTargetInstance(BoundExpression thisExpr, MethodSymbol method)

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#369]
PeachPie PHP Compiler version 0.9.36

The below exception is thrown without referencing PHP code. 
Is there a way to change the verbose resp. debug level to see which code causies this issue?

```
  Unhandled Exception: System.AggregateException: One or more errors occurred. (The method or operation is not implemented.) ---> System.NotImplementedException: The method or operation is not implemented.
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.LoadTargetInstance(BoundExpression thisExpr, MethodSymbol method)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitCall(ILOpCode code, MethodSymbol method, BoundExpression thisExpr, ImmutableArray`1 arguments, BoundTypeRef staticType)
     at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.EmitDirectCall(CodeGenerator cg, ILOpCode opcode, MethodSymbol method, BoundTypeRef staticType)
     at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.Emit(CodeGenerator cg)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitSpecialize(BoundExpression expr)
     at Pchp.CodeAnalysis.Semantics.BoundCopyValue.Emit(CodeGenerator cg)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to)
     at Pchp.CodeAnalysis.Semantics.BoundReturnStatement.Emit(CodeGenerator cg)
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Emit(CodeGenerator cg)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
     at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Generate(CodeGenerator cg)
     at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
     at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
     at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBody(SourceRoutineSymbol routine)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica.Execute()
     --- End of inner exception stack trace ---
     at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
     at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
     at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
     at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBodies()
     at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.PhpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
     at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
     at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
     at Pchp.CodeAnalysis.CommandLine.PhpCompilerDriver.Run(CommandLineParser parser, String responseFile, String[] args, String clientDirectory, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories, IAnalyzerAssemblyLoader analyzerLoader, TextWriter output)
     at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
```

**Comment by jakubmisek** [comment]
Verbose will be added.
This error is caused by a call `X::foo();` where `foo` is non-static method.

**Comment by menturion** [comment]
Thanks a lot!
Have to wait for the next bug fix release to continue trying to compile the project.

**Comment by jakubmisek** [comment]
Just created NuGet feed with latest built
\>\> https://ci.appveyor.com/nuget/peachpie <<

Use PeachPie from this feed to get always latest compiler and runtime that pass tests

**Comment by menturion** [comment]
Thanks.
I updated to prerelease versions 1.0.0-appv2297 and got the same exception messages as reported above with no additional information.

**Comment by jakubmisek** [comment]
Thank you.
Not even a php source file name? Are you compiling in debug mode?

**Comment by menturion** [comment]
I'm sorry, no PHP file referenced. Solution config is set to debug.
Please find the latest build attempt below:

------ Build started: Project: vendor, Configuration: Debug Any CPU ------
PeachPie PHP Compiler version 0.9.36+c4b77894f8368e45598047e9937668d64d2db922

Unhandled Exception: System.AggregateException: One or more errors occurred. (The method or operation is not implemented.) ---> System.NotImplementedException: The method or operation is not implemented.
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.LoadTargetInstance(BoundExpression thisExpr, MethodSymbol method)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitCall(ILOpCode code, MethodSymbol method, BoundExpression thisExpr, ImmutableArray`1 arguments, BoundTypeRef staticType)
   at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.EmitDirectCall(CodeGenerator cg, ILOpCode opcode, MethodSymbol method, BoundTypeRef staticType)
   at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitSpecialize(BoundExpression expr)
   at Pchp.CodeAnalysis.Semantics.BoundCopyValue.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to)
   at Pchp.CodeAnalysis.Semantics.BoundReturnStatement.Emit(CodeGenerator cg)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
   at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Generate(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
   at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBody(SourceRoutineSymbol routine)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBodies()
   at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Pchp.CodeAnalysis.PhpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Pchp.CodeAnalysis.CommandLine.PhpCompilerDriver.Run(CommandLineParser parser, String responseFile, String[] args, String clientDirectory, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories, IAnalyzerAssemblyLoader analyzerLoader, TextWriter output)
   at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)

**Comment by jakubmisek** [comment]
This is still the 0.9.36 version

**Comment by menturion** [comment]
Sorry, mea culpa.
Thought, that the update VS made by adding ...

```
  <ItemGroup>
    <PackageReference Update="Peachpie.Compiler.Tools" Version="1.0.0-appv2297" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Peachpie.App" Version="1.0.0-appv2297" />
  </ItemGroup>
```

... would do the magic.
Now, I changed the SDK manually to "<Project Sdk="Peachpie.NET.Sdk/1.0.0-appv2297">".

**Comment by menturion** [comment]
Here is the new exception message with more details:

------ Build started: Project: vendor, Configuration: Debug Any CPU ------
PeachPie PHP Compiler version 1.0.0-appv2297+556f44dff9142cad1e0c949b43b043b4415e87ce

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ( not implemented at C:\dotnetvendor\vendor\zendframework\zend-cache\src\Storage\Adapter\Filesystem.php(546, 12)) ---> System.NotImplementedException:  not implemented at C:\dotnetvendor\vendor\zendframework\zend-cache\src\Storage\Adapter\Filesystem.php(546, 12)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.LoadTargetInstance(BoundExpression thisExpr, MethodSymbol method)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitCall(ILOpCode code, MethodSymbol method, BoundExpression thisExpr, ImmutableArray`1 arguments, BoundTypeRef staticType)
   at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.EmitDirectCall(CodeGenerator cg, ILOpCode opcode, MethodSymbol method, BoundTypeRef staticType)
   at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitSpecialize(BoundExpression expr)
   at Pchp.CodeAnalysis.Semantics.BoundCopyValue.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to)
   at Pchp.CodeAnalysis.Semantics.BoundReturnStatement.Emit(CodeGenerator cg)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
   at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Generate(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
   at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBody(SourceRoutineSymbol routine)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBodies()
   at Pchp.CodeAnalysis.SourceCompiler.CompileSources(PhpCompilation compilation, PEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Pchp.CodeAnalysis.PhpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Pchp.CodeAnalysis.CommandLine.PhpCompilerDriver.Run(CommandLineParser parser, String responseFile, String[] args, String clientDirectory, String baseDirectory, String sdkDirectory, String additionalReferenceDirectories, IAnalyzerAssemblyLoader analyzerLoader, TextWriter output)
   at Peachpie.NETCore.Compiler.Tools.Program.Main(String[] args)
```

**Comment by jakubmisek** [comment]
@menturion thanks, and what's on `C:\dotnetvendor\vendor\zendframework\zend-cache\src\Storage\Adapter\Filesystem.php(546, 12)` ?

**Comment by menturion** [comment]
Have a look: 
https://github.com/zendframework/zend-cache/blob/72c16e430a69f758827b53d55ca0cb6be8c10184/src/Storage/Adapter/Filesystem.php#L546

```
    public function getItem($key, & $success = null, & $casToken = null)
    {
        $options = $this->getOptions();
        if ($options->getReadable() && $options->getClearStatCache()) {
            clearstatcache();
        }
        $argn = func_num_args();
        if ($argn > 2) {
            return parent::getItem($key, $success, $casToken);
        } elseif ($argn > 1) {
            return parent::getItem($key, $success);
        }
        return parent::getItem($key);
    }
```

**Comment by jakubmisek** [comment]
@menturion you have to take a look on your version of sources, it might differ
`546: if ($argn > 2) {` has no method call on it

**Comment by menturion** [comment]
I am also wondering.  The local file "Filesystem.php" that has thrown the exception and the above referenced file in the "zendframework" repository are identical.

I have triple-checked this.  This part (546, 12) of the code is referenced. 
Also tested with PeachPie PHP Compiler version 1.0.0-appv2298+50c36f30257a5c94677a663f4ae9845077f8a2cb.

**Comment by menturion** [comment]
Today, I have tested this issue again by creating a fresh new dotnet project and a fresh new vendor install (by "composer install --no-dev") to avoid any side effects:

Composer JSON file contains just:

```
{
    "require": {
        "zendframework/zend-cache": "^2.8"
    }
}
```

Same result. Exception points to the same code within the same file, i.e. ...
C:\dotnetvendor\vendor\zendframework\zend-cache\src\Storage\Adapter\Filesystem.php(546, 12)

Maybe you could easily reproduce this issue by using this simple setup.

**Comment by jakubmisek** [comment]
Maybe we index lines starting from `0` :) 

If you're using Visual Studio, you can double-click the error to navigate to the right location.

Anyways;
thank you for the `composer.json` file, I'll definitely try it. We probably incorrectly resolve `parent::` type which causes this unexpected behavior... I'll keep you informed!

**Comment by menturion** [comment]
Thanks.
This is shown as final error msg in VS:

`[path]\.nuget\packages\peachpie.net.sdk\1.0.0-appv2298\build\Peachpie.NET.Core.Sdk.targets(167,5): error MSB3073: The command "dotnet "[path]\.nuget\packages\peachpie.compiler.tools\1.0.0-appv2298\build\../tools/dotnet-compile-php.dll" @obj\Debug\netstandard2.0\compile-php-args.rsp" exited with code -532462766.`

When double clicking on the error MSB3073 it points to ...

`<Exec Command="dotnet &quot;$(PeachpieToolFullPath)&quot; @$(TempOutputDir)compile-php-args.rsp" />`

... in [path]\.nuget\packages\peachpie.net.sdk\1.0.0-appv2298\build\Peachpie.NET.Core.Sdk.targets

**Comment by jakubmisek** [comment]
Thank you, the latest commit fixes the compilation.

There will be more issues I guess, also the analysis can be improved significantly to produce smaller and faster DLL but that;s for another issue. Thanks for the detailed info!

**Comment by menturion** [comment]
I thank you. This issue is fixed. Vendor libs built sucessfully with lots of warnings, using PeachPie PHP Compiler version 1.0.0-appv2300+8c88879ed464ffb42a23a2736fe267c65e15bd44.
Can't judge how severe these warnings are.
