### ISSUE TITLE
xinclude in XmlDom extension not implemented

### ISSUE THREAD

**Issue by bfistein** [peachpiecompiler/peachpie#415]
PHPUnit uses `xinclude` in the XmlDom extension. Exception details below:

```
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at Peachpie.Library.XmlDom.DOMDocument.xinclude(Int32 options)
   at PHPUnit.Util.Xml.load(Context <ctx>, PhpValue actual, PhpValue isHtml, PhpValue filename, PhpValue xinclude, PhpValue strict) in C:\Development\laravel-peachpie-sample\Laravel\vendor\phpunit\phpunit\src\Util\Xml.php:line 87
   at PHPUnit.Util.Xml.loadFile(Context <ctx>, PhpValue filename, PhpValue isHtml, PhpValue xinclude, PhpValue strict) in C:\Development\laravel-peachpie-sample\Laravel\vendor\phpunit\phpunit\src\Util\Xml.php:line 143
   at PHPUnit.Util.Configuration.__construct(PhpValue filename) in C:\Development\laravel-peachpie-sample\Laravel\vendor\phpunit\phpunit\src\Util\Configuration.php:line 84
   at PHPUnit.Util.Configuration..ctor(Context <ctx>, PhpValue filename)
   at PHPUnit.Util.Configuration.getInstance(Context <ctx>, PhpValue filename) in C:\Development\laravel-peachpie-sample\Laravel\vendor\phpunit\phpunit\src\Util\Configuration.php:line 70
   at PHPUnit.TextUI.Command.handleArguments(PhpValue argv) in C:\Development\laravel-peachpie-sample\Laravel\vendor\phpunit\phpunit\src\TextUI\Command.php:line 847
   at PHPUnit.TextUI.Command.run(PhpValue argv, PhpValue exit) in C:\Development\laravel-peachpie-sample\Laravel\vendor\phpunit\phpunit\src\TextUI\Command.php:line 174
   at PHPUnit.TextUI.Command.main(Context <ctx>, PhpTypeInfo <static>, PhpValue exit) in C:\Development\laravel-peachpie-sample\Laravel\vendor\phpunit\phpunit\src\TextUI\Command.php:line 163
   at <Root>.main_php.main(Context <ctx>) in C:\Development\laravel-peachpie-sample\Laravel\main.php:line 54
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Development\laravel-peachpie-sample\Laravel\main.php:line 58
   at <Script>.Main(String[] args)
```

**Comment by diddledan** [comment]
This also affects PHPUnit 5 (this older version is needed when testing WordPress code)
