### ISSUE TITLE
Issue using multiple script assemblies

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#417]
I'm trying to separate the Laravel code into its own Laravel.dll and the website code
into website.dll. This requires that website.dll calls some Laravel classes from PHP.

When running I keep running into the following debug assertion:
```
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----

---- Assert Long Message ----

   at Pchp.Core.Dynamic.TargetTypeParam.Pchp.Core.Dynamic.ISpecialParamHolder.Process(CallSiteContext info, Expression valueExpr)
   at Pchp.Core.Dynamic.CallSiteContext.ProcessArg(DynamicMetaObject arg)
   at Pchp.Core.Dynamic.CallSiteContext.ProcessArgs(DynamicMetaObject target, DynamicMetaObject[] args, Boolean hasTargetInstance)
   at Pchp.Core.Dynamic.CallBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Illuminate.Http.Request.capture(Context <ctx>, PhpTypeInfo <static>) in C:\Development\laravel-peachpie-sample\Laravel\src\Illuminate\Http\Request.php:line 57
   at <Root>public.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Development\laravel-peachpie-sample\website\public/index.php:line 58
   at <Root>public.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.<>c__DisplayClass7_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

It happens at https://github.com/calvinbaart/laravel-peachpie-sample/blob/feature/laravel-sdk/Laravel/src/Illuminate/Http/Request.php#L57

The code is called from another assembly at https://github.com/calvinbaart/laravel-peachpie-sample/blob/feature/laravel-sdk/website/public/index.php#L59

I'll try to create smaller minimal test case

**Comment by calvinbaart** [comment]
Finally got around making a sample for this one. Calling static from a function called from another assembly crashes it.

Sample is here: https://github.com/calvinbaart/bug-sample-peachpie-multi-assembly

Calling ``TestClass::now1`` or ``TestClass::now2`` from App crashes the code. ``TestClass::now3``works even though it functionally does the same as ``TestClass::now2``
