### ISSUE TITLE
Mockery: eval doesn't autoload classes

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#422]
Suppose we have a test.php with these contents:
```php
<?php

class TestClass
{
}
```

When executing the following code PeachPie will throw an exception saying TestClass can't be found:
```php
spl_autoload_register(function ($class) {
    require "test.php";
});

eval("new TestClass();");
```

On PHP this works as expected (program ends without output or exception)

**Comment by jakubmisek** [comment]
works for me, internally there is nothing that would prevent autoloading from within `eval`

**Comment by jakubmisek** [comment]
closing the issue for now, if there would be any more specific issue, we'll re-open it : )

**Comment by calvinbaart** [comment]
I'm still getting this issue. Can't seem to be able to get a minimal-test-case :/

I have setup a project here: https://github.com/calvinbaart/laravel-peachpie-sample/tree/feature/laravel-sdk

When running the Laravel.Tests project I get the following error:

```
Unhandled Exception: System.InvalidOperationException: Class 'Mockery' not found
   at Pchp.Core.DefaultErrorHandler.Throw(PhpError error, String message)
   at Peachpie.Library.Scripting.Script.<>c__DisplayClass15_0.<CreateInvalid>b__0(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.Library.Scripting.Script.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Operators.Eval(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self, String code, String currentpath, Int32 line, Int32 column)
   at Mockery.Loader.EvalLoader.load(MockDefinition definition) in /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php:line 37
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at Mockery.Container.mock(PhpValue[] args) in /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/vendor/mockery/mockery/library/Mockery/Container.php:line 230
   at <>.mock(Container , PhpValue[] )
   at Mockery.mock(Context <ctx>, PhpValue[] args)
   at Illuminate.Tests.Auth.AuthDatabaseTokenRepositoryTest.getRepo()
   at Illuminate.Tests.Auth.AuthDatabaseTokenRepositoryTest.testCreateInsertsNewRecordIntoTable()
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , TestCase , NameParam`1 , Context , UnpackingParam`1 )
   at PHPUnit.Framework.TestCase.runTest()
   at PHPUnit.Framework.TestCase.runBare()
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , PhpValue , Context )
   at PHPUnit.Framework.TestResult.run(Test test)
   at PHPUnit.Framework.TestCase.run(TestResult result)
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at PHPUnit.Framework.TestSuite.run(TestResult result)
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at PHPUnit.Framework.TestSuite.run(TestResult result)
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at PHPUnit.TextUI.TestRunner.doRun(Test suite, PhpArray arguments, Boolean exit)
   at PHPUnit.TextUI.Command.run(PhpArray argv, Boolean exit)
   at PHPUnit.TextUI.Command.main(Context <ctx>, PhpTypeInfo <static>, Boolean exit)
   at <Root>.main_php.main(Context <ctx>)
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Script>.Main(String[] args)
```

Even though Mockery is available for auto-loading outside of the eval. Mockery generates the following code for the eval: https://pastebin.com/Cdi3nTkh

**Comment by calvinbaart** [comment]
Alright, I think I figured it out @jakubmisek 

Have Assembly1 with testclass.php:
```php
<?php

class TestClass
{
}
```

and Assembly2 with test.php:
```php
<?php

spl_autoload_register(function ($class) {
    require "testclass.php";
});

eval("class NewClass extends TestClass { public function test() { echo 'test123'; } }");

$obj = new NewClass();
$obj->test();
```

In PeachPie I'm getting the following error:
```
Unhandled Exception: System.InvalidOperationException: Type name 'TestClass' could not be resolved.
   at Pchp.Core.DefaultErrorHandler.Throw(PhpError error, String message)
   at Peachpie.Library.Scripting.Script.<>c__DisplayClass15_0.<CreateInvalid>b__0(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.Library.Scripting.Script.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Operators.Eval(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self, String code, String currentpath, Int32 line, Int32 column)
   at <Root>.test_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in /Users/calvinbaart/Development/peachpie-bug-sample/assembly2/test.php:line 7
   at <Script>.Main(String[] args)
```

It does work correctly when executing it without the eval:
```php
<?php

spl_autoload_register(function ($class) {
    require "testclass.php";
});

class NewClass extends TestClass { public function test() { echo 'test123'; } }
// eval("class NewClass extends TestClass { public function test() { echo 'test123'; } }");

$obj = new NewClass();
$obj->test();
```

It also works with eval when both test.php and testclass.php are in the same assembly

**Comment by calvinbaart** [comment]
I have created a sample here: https://github.com/calvinbaart/bug-peachpie-eval
