### ISSUE TITLE
Generator in closure causes NotImplementedException when accessing fields

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#449]
Test case:
```php
class A
{
  private $foo;

  private function bar()
  {
    return function() {
      $this->foo = 42;
      yield 42;
    };
  }

  public function test() {
    foreach ($this->bar()() as $v) {
      echo $v;
    }
  }
}

(new A)->test();
```
Expected result:
```
42
```
Actual result:
```
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at Pchp.Core.Dynamic.SetFieldBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args) in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\Dynamic\SetFieldBinder.cs:line 58
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at <Root>.index_php.<>sm_anonymous@function(Context <ctx>, Object this, PhpArray <locals>, PhpArray <tmpLocals>, Generator generator) in C:\robert\iolevel\peachpie\src\Tests\Peachpie.Test\bin\Debug\netcoreapp2.0\index.php:line 10
   at Generator.moveStateMachine() in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\std\Generator.cs:line 205
   at Generator.checkIfRunToFirstYieldIfNotRun() in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\std\Generator.cs:line 225
   at Generator.rewind() in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\std\Generator.cs:line 99
   at Pchp.Core.Operators.PhpIteratorEnumerator.Reset() in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\Operators.cs:line 806
   at Pchp.Core.Operators.PhpIteratorEnumerator..ctor(Iterator iterator) in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\Operators.cs:line 750
   at Pchp.Core.Operators.GetForeachEnumerator(Iterator it) in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\Operators.cs:line 1106
   at Pchp.Core.Operators.GetForeachEnumerator(Object obj, Boolean aliasedValues, RuntimeTypeHandle caller) in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\Operators.cs:line 1120
   at Pchp.Core.PhpValue.ClassTable.GetForeachEnumerator(PhpValue& me, Boolean aliasedValues, RuntimeTypeHandle caller) in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\PhpValue.TypeTable.cs:line 522
   at Pchp.Core.PhpValue.GetForeachEnumerator(Boolean aliasedValues, RuntimeTypeHandle caller) in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\PhpValue.cs:line 411
   at Pchp.Core.Operators.GetForeachEnumerator(PhpValue value, Boolean aliasedValues, RuntimeTypeHandle caller) in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\Operators.cs:line 1178
   at A.test() in C:\robert\iolevel\peachpie\src\Tests\Peachpie.Test\bin\Debug\netcoreapp2.0\index.php:line 16
   at <Root>.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\robert\iolevel\peachpie\src\Tests\Peachpie.Test\bin\Debug\netcoreapp2.0\index.php:line 22
   at <Root>.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self) in C:\robert\iolevel\peachpie\src\Peachpie.Runtime\Context.ScriptsMap.cs:line 96
   at Peachpie.Library.Scripting.Script.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self) in C:\robert\iolevel\peachpie\src\Peachpie.Library.Scripting\Context.Script.cs:line 296
   at Peachpie.Test.Program.Main(String[] args) in C:\robert\iolevel\peachpie\src\Tests\Peachpie.Test\Program.cs:line 35
```

**Comment by jakubmisek** [comment]
@roberthusak fixed! thanks for the test case Robert. 

May I ask you to add this test case into the `tests` folder?

**Comment by roberthusak** [comment]
@jakubmisek Great, thanks! Sure, added in 3133bef88d65fb2f94e16862e06f4be8e4349861.
