### ISSUE TITLE
C# exceptions don't implement \Throwable

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#474]
In the following sample:
```php
class TestClass
{
    function test(TestClass $cls)
    {
    }
}

try {
    $obj = new TestClass();
    $obj->test(null);
} catch (\Throwable $e) {
    echo "CATCHED:\r\n";
    print_r($e);
}
```

PHP outputs:
```
CATCHED:
TypeError Object
(
    [message:protected] => Argument 1 passed to TestClass::test() must be an instance of TestClass, null given, called in /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php on line 41
    [string:Error:private] =>
    [code:protected] => 0
    [file:protected] => /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php
    [line:protected] => 34
    [trace:Error:private] => Array
        (
            [0] => Array
                (
                    [file] => /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php
                    [line] => 41
                    [function] => test
                    [class] => TestClass
                    [type] => ->
                    [args] => Array
                        (
                            [0] =>
                        )

                )

        )

    [previous:Error:private] =>
)
```

while PeachPie crashes with the following output:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: cls
   at Pchp.Core.PhpException.ArgumentNullError(String argument)
   at TestClass.test(TestClass cls) in /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php:line 34
   at CallSite.Target(Closure , CallSite , PhpValue , Context , CallerTypeParam , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php:line 41
   at <Script>.Main(String[] args)
```

The same happens with exceptions passed to the error handler. This causes alot of PHP exception handlers to fail because the assumption in PHP is that all exceptions implement \Throwable

**Comment by jakubmisek** [comment]
Seems we throw `System.ArgumentNullException` instead of `TypeError`.
