### ISSUE TITLE
preg_match (and other PCRE functions) throws exception instead of warning

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#475]
In the following sample:
```php
if (preg_match("test123", "test123")) {
    echo "match";
} else {
    echo "no match";
}
```

PHP outputs the following:
```
PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php on line 32

Warning: preg_match(): Delimiter must not be alphanumeric or backslash in /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php on line 32
no match
```

PeachPie crashes with the following error:
```
Unhandled Exception: System.ArgumentException: Delimiter must not be alphanumeric or backslash
   at Peachpie.Library.RegularExpressions.RegexParser.TrimDelimiters(String re, Int32 end)
   at Peachpie.Library.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at Peachpie.Library.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at Pchp.Library.PCRE.preg_match(Context ctx, String pattern, String subject)
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php:line 32
   at <Script>.Main(String[] args)
```

PHPUnit explicitly checks for warnings and ignores them in preg_match when using the filter argument. This fails under PeachPie.

**Comment by jakubmisek** [comment]
Right, internally we throw exceptions in .NET manner. Here we should probably handle it and output the warning as in PHP.

Note: in a future version, we'll probably won't even allow to compile this code since we'll analyse the regullar ex. in compile time.

**Comment by jakubmisek** [comment]
Probably we should implement `preg_last_error()` as well
