### ISSUE TITLE
mb_substr fails when giving null as length

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#483]
Sample:
```php
function substr2($string, $start, $length = null)
{
    return mb_substr($string, $start, $length, 'UTF-8');
}

echo substr2("hello", 1) . "\r\n";
```

PeachPie output:
```
```

PHP output:
```
ello
```

According to the PHP documentation when length is omitted or NULL it should extract all characters to the end of the string: https://www.php.net/manual/en/function.mb-substr.php

It should also be noted that calling mb_substr directly with NULL argument for length likes this:
```php
echo mb_substr("hello", 1, null, "UTF-8") . "\r\n";
```

produces this exception:
```
Unhandled Exception: System.NotImplementedException: System.Object -> long
   at Pchp.Core.Dynamic.ConvertExpression.BindToLong(Expression expr)
   at Pchp.Core.Dynamic.ConvertExpression.Bind(Expression arg, Type target, Expression ctx)
   at Pchp.Core.Dynamic.BinderHelpers.BindToCall(Expression instance, MethodBase method, Expression ctx, ArgumentsBinder args, Boolean isStaticCallSyntax, PhpTypeInfo lateStaticType)
   at Pchp.Core.Dynamic.OverloadBinder.BindOverloadCall(Type treturn, Expression target, MethodBase[]& methods, Expression ctx, ArgumentsBinder args, Boolean isStaticCallSyntax, PhpTypeInfo lateStaticType)
   at Pchp.Core.Dynamic.OverloadBinder.BindOverloadCall(Type treturn, Expression target, MethodBase[] methods, Expression ctx, Expression[] args, Boolean isStaticCallSyntax, PhpTypeInfo lateStaticType)
   at Pchp.Core.Dynamic.CallBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in /Users/calvinbaart/Development/laravel-peachpie-sample/Laravel.Tests/main.php:line 32
   at <Script>.Main(String[] args)
```

**Comment by jakubmisek** [comment]
seems `NULL` is incorrectly interpreted as `0`, plus in dynamic compilation (this issue) it fails to convert NULL at all

**Comment by jakubmisek** [comment]
@calvinbaart you shouldn't see the exception - it is caused by dynamic invocation which cannot happen for `mb_substr`. The only possible cause of this might be that you have referenced two different versions of `Peachpie.Library` so runtime is constantly dealing with ambiguities of two different `mb_substr` from two different assemblies?

**Comment by calvinbaart** [comment]
Thats weird, I looked through all the files but they all reference the local 0.9.9-dev build. Just in case I cleared out all the bin and obj folders, rebuild peachpie itself, cleared the nuget cache and rebuild but I still get the exception

**Comment by jakubmisek** [comment]
No big deal for now, but compiler should not be invoking the `mb_substr` dynamically in this case. At least it does not for me.
