### ISSUE TITLE
Calling defined with static causes exception

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#498]
Sample:
```php
class TestClass
{
    const TEST_CONSTANT = 10;

    public function test()
    {
        return defined("static::TEST_CONSTANT");
    }
}

$obj = new TestClass();
echo (int) $obj->test();
```

PeachPie output:
```
Unhandled Exception: System.NotSupportedException: Specified method is not supported.
   at Pchp.Core.Context.ResolveType(String name, RuntimeTypeHandle callerCtx, Boolean autoload)
   at Pchp.Library.Constants.defined(Context ctx, RuntimeTypeHandle callerCtx, String name)
   at TestClass.test() in /mnt/c/Development/laravel-peachpie-sample/Laravel.Tests/main.php:line 43
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in /mnt/c/Development/laravel-peachpie-sample/Laravel.Tests/main.php:line 48
   at <Script>.Main(String[] args)
```

PHP output:
```
1
```

**Comment by jakubmisek** [comment]
Note: This can be implemented inside instance functions like in the sample. We won't be able to efficiently implement this in static methods.

**Comment by jakubmisek** [comment]
fixed, but note - calling inside a static method still causes an exception (`Error: Cannot access static:: when no class scope is active`)
