### ISSUE TITLE
Peachpie.NET.Core.Sdk.targets (line #190): Value does not fall within the expected range 

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#519]
I am getting the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Value does not fall within the expected range.
   at Pchp.CodeAnalysis.Semantics.PhpOperationExtensions.PhpSerialize(StringBuilder result, BoundArrayEx array)
   at Pchp.CodeAnalysis.Semantics.PhpOperationExtensions.PhpSerializeOrThrow(BoundArrayEx array)
   at Pchp.CodeAnalysis.Symbols.SourceParameterSymbol.<GetCustomAttributesToEmit>d__48.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 customAttributes)
   at Microsoft.Cci.MetadataVisitor.Visit(IParameterDefinition parameterDefinition)
   at Microsoft.Cci.MetadataVisitor.Visit(ImmutableArray`1 parameters)
   at Microsoft.Cci.MetadataVisitor.Visit(IMethodDefinition method)
   at Microsoft.Cci.ReferenceIndexerBase.Visit(IMethodDefinition method)
   at Pchp.CodeAnalysis.Symbols.MethodSymbol.Microsoft.Cci.IReference.Dispatch(MetadataVisitor visitor)
   at Microsoft.Cci.MetadataVisitor.Visit(ITypeDefinitionMember typeMember)
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 methods)
   at Microsoft.Cci.ReferenceIndexerBase.Visit(ITypeDefinition typeDefinition)
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 types)
   at Microsoft.Cci.ReferenceIndexer.Visit(CommonPEModuleBuilder module)
   at Microsoft.Cci.MetadataWriter.CreateIndices()
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
   at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, Boolean includePrivateMembers, Boolean emitTestCoverageData, String pePdbFilePath, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Peachpie.NET.Sdk.Tools.BuildTask.Execute()	app	\.nuget\packages\peachpie.net.sdk\1.0.0-appv2788\build\Peachpie.NET.Core.Sdk.targets	190

**Comment by jakubmisek** [comment]
Thanks, caused by a default parameter value of type array containing something that is not a literal probably. Will add more details into the exception.

**Comment by menturion** [comment]
Thanks. 
Here comes the update: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unexpected value 'Pchp.CodeAnalysis.Semantics.BoundCopyValue' of type 'Pchp.CodeAnalysis.Semantics.BoundCopyValue'
   at Pchp.CodeAnalysis.Semantics.PhpOperationExtensions.PhpSerialize(StringBuilder result, BoundArrayEx array)
   at Pchp.CodeAnalysis.Semantics.PhpOperationExtensions.PhpSerializeOrThrow(BoundArrayEx array)
   at Pchp.CodeAnalysis.Symbols.SourceParameterSymbol.<GetCustomAttributesToEmit>d__48.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 customAttributes)
   at Microsoft.Cci.MetadataVisitor.Visit(IParameterDefinition parameterDefinition)
   at Microsoft.Cci.MetadataVisitor.Visit(ImmutableArray`1 parameters)
   at Microsoft.Cci.MetadataVisitor.Visit(IMethodDefinition method)
   at Microsoft.Cci.ReferenceIndexerBase.Visit(IMethodDefinition method)
   at Pchp.CodeAnalysis.Symbols.MethodSymbol.Microsoft.Cci.IReference.Dispatch(MetadataVisitor visitor)
   at Microsoft.Cci.MetadataVisitor.Visit(ITypeDefinitionMember typeMember)
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 methods)
   at Microsoft.Cci.ReferenceIndexerBase.Visit(ITypeDefinition typeDefinition)
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 types)
   at Microsoft.Cci.ReferenceIndexer.Visit(CommonPEModuleBuilder module)
   at Microsoft.Cci.MetadataWriter.CreateIndices()
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
   at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, Boolean includePrivateMembers, Boolean emitTestCoverageData, String pePdbFilePath, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Peachpie.NET.Sdk.Tools.BuildTask.Execute()	app	\.nuget\packages\peachpie.net.sdk\1.0.0-appv2791\build\Peachpie.NET.Core.Sdk.targets	190

**Comment by jakubmisek** [comment]
thanks, try it now please, it might report something else

**Comment by menturion** [comment]
Below is the current error message:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unexpected value 'Pchp.CodeAnalysis.Semantics.BoundFieldRef' of type 'Pchp.CodeAnalysis.Semantics.BoundFieldRef'
   at Pchp.CodeAnalysis.Semantics.PhpOperationExtensions.PhpSerialize(StringBuilder result, Object value)
   at Pchp.CodeAnalysis.Semantics.PhpOperationExtensions.PhpSerialize(StringBuilder result, BoundArrayEx array)
   at Pchp.CodeAnalysis.Semantics.PhpOperationExtensions.PhpSerializeOrThrow(BoundArrayEx array)
   at Pchp.CodeAnalysis.Symbols.SourceParameterSymbol.<GetCustomAttributesToEmit>d__48.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 customAttributes)
   at Microsoft.Cci.MetadataVisitor.Visit(IParameterDefinition parameterDefinition)
   at Microsoft.Cci.MetadataVisitor.Visit(ImmutableArray`1 parameters)
   at Microsoft.Cci.MetadataVisitor.Visit(IMethodDefinition method)
   at Microsoft.Cci.ReferenceIndexerBase.Visit(IMethodDefinition method)
   at Pchp.CodeAnalysis.Symbols.MethodSymbol.Microsoft.Cci.IReference.Dispatch(MetadataVisitor visitor)
   at Microsoft.Cci.MetadataVisitor.Visit(ITypeDefinitionMember typeMember)
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 methods)
   at Microsoft.Cci.ReferenceIndexerBase.Visit(ITypeDefinition typeDefinition)
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 types)
   at Microsoft.Cci.ReferenceIndexer.Visit(CommonPEModuleBuilder module)
   at Microsoft.Cci.MetadataWriter.CreateIndices()
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
   at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, Boolean includePrivateMembers, Boolean emitTestCoverageData, String pePdbFilePath, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Peachpie.NET.Sdk.Tools.BuildTask.Execute()	app	\.nuget\packages\peachpie.net.sdk\1.0.0-appv2792\build\Peachpie.NET.Core.Sdk.targets	190

**Comment by jakubmisek** [comment]
seems like a class constant - can you find it in your code? a default parameter value as array and class constant, something like
```php
function foo($a = array( MyClass::C ) ) { ... }
```

**Comment by menturion** [comment]
Unfortunately the error does not reference any code. So this will be very difficult because a lot of new code has been added between the last tested releases.

**Comment by jakubmisek** [comment]
added more details to the exception

**Comment by menturion** [comment]
It took a while.
Below is the updated exception:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot construct serialized parameter default value. Routine 'addMetadataSP20' in simplesamlphp/lib/SimpleSAML/Metadata/SAMLBuilder.php, Unexpected value 'Pchp.CodeAnalysis.Semantics.BoundFieldRef' of type 'Pchp.CodeAnalysis.Semantics.BoundFieldRef'.
   at Pchp.CodeAnalysis.Symbols.SourceParameterSymbol.<GetCustomAttributesToEmit>d__48.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 customAttributes)
   at Microsoft.Cci.MetadataVisitor.Visit(IParameterDefinition parameterDefinition)
   at Microsoft.Cci.MetadataVisitor.Visit(ImmutableArray`1 parameters)
   at Microsoft.Cci.MetadataVisitor.Visit(IMethodDefinition method)
   at Microsoft.Cci.ReferenceIndexerBase.Visit(IMethodDefinition method)
   at Pchp.CodeAnalysis.Symbols.MethodSymbol.Microsoft.Cci.IReference.Dispatch(MetadataVisitor visitor)
   at Microsoft.Cci.MetadataVisitor.Visit(ITypeDefinitionMember typeMember)
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 methods)
   at Microsoft.Cci.ReferenceIndexerBase.Visit(ITypeDefinition typeDefinition)
   at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 types)
   at Microsoft.Cci.ReferenceIndexer.Visit(CommonPEModuleBuilder module)
   at Microsoft.Cci.MetadataWriter.CreateIndices()
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
   at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, Boolean includePrivateMembers, Boolean emitTestCoverageData, String pePdbFilePath, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Peachpie.NET.Sdk.Tools.BuildTask.Execute()	app	\.nuget\packages\peachpie.net.sdk\1.0.0-appv2793\build\Peachpie.NET.Core.Sdk.targets	190	

The affected file is: 
simplesamlphp/lib/SimpleSAML/Metadata/SAMLBuilder.php 
of SimpleSAMLphp v1.17.2:
https://github.com/simplesamlphp/simplesamlphp/releases/tag/v1.17.2

**Comment by jakubmisek** [comment]
https://github.com/simplesamlphp/simplesamlphp/blob/39ea6b62447009037ba8a99324c8128c7409a568/lib/SimpleSAML/Metadata/SAMLBuilder.php#L480

seems like the class `\SAML2\Constants` was not resolved, is it compiled within the project properly?

**Comment by menturion** [comment]
Compilation stopped with this exception.
Where can I check the progress of the compilation process?

**Comment by jakubmisek** [comment]
Basically you cannot, we have to resolve the exception first.

Is the `SAML2\Constants` class part of your source code? Isn't it declared twice in different files?

**Comment by menturion** [comment]
As far as I can see now, only once, but I'll have to take a closer look later.

**Comment by jakubmisek** [comment]
nevermind, found the test case :) :
```php
class Constants {
    const NS_SAMLP = 'hello';
}

class X {
    public function addMetadataSP20($metadata, $protocols = [\Constants::NS_SAMLP]) {
    }
}
```

**Comment by menturion** [comment]
Great, many thanks.
Just tested. Building the project succeeded.
