### ISSUE TITLE
System.InvalidOperationException: Expected state to be Failed but was Connected in MySqlConnector.dll

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#532]
in https://github.com/nulastudio/ecshop/blob/a1b5ac8730be85e46cebf01f4c032e81169733e7/upload/includes/cls_mysql.php#L267

but unfortunately i can't provide a test case, because the test case just works as good as expected. and this always happens under osx, but sometimes happens under windows and if i don't add any breakpoint, most of times is fine! they are the same `5.7` version of mysql.

here is the exception stack
```
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in MySqlConnector.dll but was not handled in user code: 'Expected state to be Failed but was Connected.'
   at MySqlConnector.Core.ServerSession.VerifyState(State state) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1277
   at MySqlConnector.Core.ServerSession.FinishQuerying() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 198
   at MySql.Data.MySqlClient.MySqlConnection.FinishQuerying(Boolean hasWarnings) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 548
   at MySql.Data.MySqlClient.MySqlDataReader.DoClose() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 445
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 282
   at System.Data.Common.DbDataReader.Dispose()
   at Peachpie.Library.MySql.MySqlConnectionResource.ClosePendingReader()
   at Pchp.Library.Database.ConnectionResource.ExecuteCommandInternal(String commandText, CommandType commandType, Boolean convertTypes, IEnumerable`1 parameters, Boolean skipResults)
   at Peachpie.Library.MySql.MySql.mysql_query(Context ctx, PhpString query, PhpResource link)
   at cls_mysql.query(PhpValue sql, PhpValue type) in /Users/imac/Projects/ecsharp/Website/ecshop/upload/includes/cls_mysql.php:line 267
   at sql_executor.do_other(PhpValue query_item) in /Users/imac/Projects/ecsharp/Website/ecshop/upload/includes/cls_sql_executor.php:line 861
   at sql_executor.query(PhpValue query_item) in /Users/imac/Projects/ecsharp/Website/ecshop/upload/includes/cls_sql_executor.php:line 264
   at sql_executor.run_all(PhpValue sql_files) in /Users/imac/Projects/ecsharp/Website/ecshop/upload/includes/cls_sql_executor.php:line 174
   at <Root>ecshop/upload/install/includes.lib_installer_php.install_data(Context <ctx>, PhpValue sql_files) in /Users/imac/Projects/ecsharp/Website/ecshop/upload/install/includes/lib_installer.php:line 386
   at <Root>ecshop/upload/install.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in /Users/imac/Projects/ecsharp/Website/ecshop/upload/install/index.php:line 345
   at <Root>ecshop/upload/install.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
```

**Comment by jakubmisek** [comment]
Seems like a similar issue has been fixed already (https://github.com/mysql-net/MySqlConnector/issues/423)

**Comment by jakubmisek** [comment]
It is important to find out, what query was called using this `$link_id` right before - there is an unfinished pending state (probably) being closed incorrectly or there a finished state that does not need to be closed.

**Comment by jakubmisek** [comment]
@liesauer can you check what was the query being executed before this happens? The sequence of called mysql functions before this exception is crucial in order to resolve this.

**Comment by liesauer** [comment]
@jakubmisek i have tried. i try to exec the same query in the test case, emmm, it works. so, i am thinking may be `https://github.com/nulastudio/ecshop/blob/a1b5ac8730be85e46cebf01f4c032e81169733e7/upload/includes/cls_mysql.php` class problem? i still working on it.

**Comment by liesauer** [comment]
finally, i  reproduced it. but the interesting thing is the web test case always has the same exception, but the console test case after occurring several times it becomes `EventSource Error: ERROR: Exception during construction of EventSource System.Collections.Concurrent.ConcurrentCollectionsEventSource: 1`.

all test under osx.
[web testcase.zip](https://github.com/peachpiecompiler/peachpie/files/3634734/webMysql.zip)
[console testcase.zip](https://github.com/peachpiecompiler/peachpie/files/3634735/mysqlTest.zip)

**Comment by jakubmisek** [comment]
thank you! will try and hopefully fix both of the issues

**Comment by jakubmisek** [comment]
@liesauer it's not throwing any exceptions for us - what version of MySql server do you use?

**Comment by liesauer** [comment]
@jakubmisek `5.7.21`. i will try it again when i get home to see if the different mysql server version causes the difference.

**Comment by liesauer** [comment]
i tried `5.7.27`  and `8.0.17` on my home's hackintosh, and the web test case just works fine. but the console test case still reporting `EventSource Error: ERROR: Exception during construction of EventSource System.Collections.Concurrent.ConcurrentCollectionsEventSource: 1`

**Comment by jakubmisek** [comment]
yes, the `EventSource` exception is something unrelated.

So the MySql exception is gone? can we close it?

**Comment by liesauer** [comment]
yes, reopen it if i get some progress.
