### ISSUE TITLE
Emitting offsetExists with string expression causes conversion to int

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#533]
Test case:
```php
function test(array $a, $s) {
  echo isset($a['foo'.$s]);
}

test(['foobar' => 42], "bar");
```
Expected result:
```
1
```
Actual result:
```
Unhandled Exception: Pchp.Library.Spl.TypeError
   at Pchp.Core.Convert.ToLongOrThrow(String value)
   at Pchp.Core.PhpString.ToLongOrThrow()
   at <Root>.main_php.test(Context <ctx>, PhpArray a, PhpValue s) in C:\robert\iolevel\peachpie-samples\console-application\main.php:line 358
   at <Root>.main_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\robert\iolevel\peachpie-samples\console-application\main.php:line 361
   at <Script>.Main(String[] args)
```
If I add the `string` type hint for `$s`, it works well.

**Comment by jakubmisek** [comment]
fixed in https://github.com/peachpiecompiler/peachpie/commits/master
