### ISSUE TITLE
__destruct in trait can cause ReflectionTypeLoadException

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#538]
The problem occurs when the trait is used by a type whose parent contains `__destruct` itself, test case:
```php
trait Destructible {
  public function __destruct() {}
}

class A {
  public function __destruct() {}
}

class B extends A {
  use Destructible;
}

new B;
```

Expected empty output, actual:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'DllLoader`1' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Declaration referenced in a method implementation cannot be a final method.  Type: 'B'.  Assembly: 'console-application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Pchp.Core.Context.DllLoaderImpl.AddScriptReference(Assembly assembly)
   at Pchp.Core.Context.DllLoader`1..cctor()
   --- End of inner exception stack trace ---
   at Pchp.Core.Context.DllLoader`1.Bootstrap()
   at <Script>.Main(String[] args)
```

**Comment by jakubmisek** [comment]
I suppose it is not just `__destruct` but any method
