### ISSUE TITLE
System.InvalidOperationException: Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#558]
I'm getting this prompted in the "Output" tab window (v1.0.0-appv2914): 

 ```
System.InvalidOperationException: Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.
   at MySql.Data.MySqlClient.MySqlCommand.set_CommandText(String value) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 202
   at Peachpie.Library.MySql.MySqlConnectionResource.CreateCommandInternal(String commandText, CommandType commandType)
   at Peachpie.Library.MySql.MySqlConnectionResource.CreateCommand(String commandText, CommandType commandType)
   at Pchp.Library.Database.ConnectionResource.ExecuteCommand(String commandText, CommandType commandType, Boolean convertTypes, IEnumerable`1 parameters, Boolean skipResults)
   at Pchp.Library.Database.ConnectionResource.ExecuteQuery(String query, Boolean convertTypes)
   at Peachpie.Library.MySql.MySqli.mysqli.query(PhpString query, Int32 resultmode)
   at Peachpie.Library.MySql.MySqli.Functions.mysqli_query(mysqli link, PhpString query, Int32 resultmode)
   at Pchp.Core.PhpCallback.Invoke(Context ctx, PhpValue[] arguments)
```

**Comment by jakubmisek** [comment]
thanks! should works ok now

**Comment by menturion** [comment]
It is working now.
