### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#568]
Getting this issue:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , PhpValue , Context )
```

**Comment by jakubmisek** [comment]
thank you, but we really need the full call stack and at least the line of PHP code where it appears

**Comment by menturion** [comment]
The PHP code wouldn't give you any further information. 

In the past, some areas worked, but now they don't work anymore. Therefore, I suspect that this is a regression. 

Since the problem occurs at a code line where a DB query is formed and executed (on a high-level), it seems likely that it has to do with the changes you recently made to the database access.

**Comment by jakubmisek** [comment]
Please, the call stack, the line of PHP code where the exception occurs. Otherwise nobody can help. What DB query, what PHP code executes the DB query, ... :)

**Comment by jakubmisek** [comment]
Sorry I have to close it, there is no information that might help to solve the issue.

Please if it happens again, post the FULL callstack, the PHP code that causes it.

**Comment by menturion** [comment]
Please find below the stack. 
I missed some lines on my first issue report. Hope this helps.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , PhpValue , Context )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , PhpValue , Context )
   at CallSite.Target(Closure , CallSite , PhpValue , Context )
   at <Root>.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.<>c__DisplayClass7_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Warning: The response has already started, the error page middleware will not be executed.
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Error: Connection ID "18230571301796315137", Request ID "8000002c-0002-fd00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
```

**Comment by jakubmisek** [comment]
thanks, do you know the line of PHP code that causes this?

**Comment by menturion** [comment]
I tried to sort this out. However, I am not able to step into it.

**Comment by jakubmisek** [comment]
when this exception happens, can you debug the process in Visual Studio and go to the stack frame
```<Root>.index_php.<Main>```
?
