### ISSUE TITLE
TypedConstant is not an array. Use Value property.

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#587]
When compiling [wpdotnet-sdk](https://github.com/iolevel/wpdotnet-sdk/commit/aa2dad8008aa9337033d6ada9d7da922f7b61cb8) in release configuration with 1.0.0-appv3051 (92369e72) the following exception occurs at compile time (it works for debug configuration):
```
TypedConstant is not an array. Use Value property.
   at Microsoft.CodeAnalysis.TypedConstant.get_Values()
   at Pchp.CodeAnalysis.Symbols.SymbolExtensions.PhpExtensionAttributeValues(AttributeData phpextensionattribute)
   at Pchp.CodeAnalysis.Semantics.Model.GlobalSymbolProvider.<>c.<get_Extensions>b__32_0(Symbol x)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Pchp.CodeAnalysis.Semantics.CompilationSymbolsExtension.HasPhpExtenion(PhpCompilation compilation, String extension_name)
   at Pchp.CodeAnalysis.FlowAnalysis.Passes.TransformationRewriter.<.ctor>b__12_5(BoundGlobalFunctionCall x)
   at Pchp.CodeAnalysis.FlowAnalysis.Passes.TransformationRewriter.VisitGlobalFunctionCall(BoundGlobalFunctionCall x)
   at Pchp.CodeAnalysis.Semantics.BoundGlobalFunctionCall.Accept[TResult](PhpOperationVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.PhpOperationVisitor`1.Accept(IPhpOperation x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitUnaryExpression(BoundUnaryEx x)
   at Pchp.CodeAnalysis.FlowAnalysis.Passes.TransformationRewriter.VisitUnaryExpression(BoundUnaryEx x)
   at Pchp.CodeAnalysis.Semantics.BoundUnaryEx.Accept[TResult](PhpOperationVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.PhpOperationVisitor`1.Accept(IPhpOperation x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitBinaryExpression(BoundBinaryEx x)
   at Pchp.CodeAnalysis.FlowAnalysis.Passes.TransformationRewriter.VisitBinaryExpression(BoundBinaryEx x)
   at Pchp.CodeAnalysis.Semantics.BoundBinaryEx.Accept[TResult](PhpOperationVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.PhpOperationVisitor`1.Accept(IPhpOperation x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGConditionalEdge(ConditionalEdge x)
   at Pchp.CodeAnalysis.FlowAnalysis.Passes.TransformationRewriter.VisitCFGConditionalEdge(ConditionalEdge x)
   at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.AcceptEdge(BoundBlock from, Edge edge)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.OnVisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.VisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor`1.Accept(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGConditionalEdge(ConditionalEdge x)
   at Pchp.CodeAnalysis.FlowAnalysis.Passes.TransformationRewriter.VisitCFGConditionalEdge(ConditionalEdge x)
   at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.AcceptEdge(BoundBlock from, Edge edge)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.OnVisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.VisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor`1.Accept(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGConditionalEdge(ConditionalEdge x)
   at Pchp.CodeAnalysis.FlowAnalysis.Passes.TransformationRewriter.VisitCFGConditionalEdge(ConditionalEdge x)
   at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.AcceptEdge(BoundBlock from, Edge edge)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.OnVisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.VisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor`1.Accept(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGSimpleEdge(SimpleEdge x)
   at Pchp.CodeAnalysis.Semantics.Graph.SimpleEdge.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.AcceptEdge(BoundBlock from, Edge edge)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.OnVisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.VisitCFGBlock(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor`1.Accept(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGConditionalEdge(ConditionalEdge x)
   at Pchp.CodeAnalysis.FlowAnalysis.Passes.TransformationRewriter.VisitCFGConditionalEdge(ConditionalEdge x)
   at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.AcceptEdge(BoundBlock from, Edge edge)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphUpdater.VisitCFGStartBlock(StartBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.OnVisitCFGStartBlock(StartBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.VisitCFGStartBlock(StartBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.StartBlock.Accept[TResult](GraphVisitor`1 visitor)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphVisitor`1.Accept(BoundBlock x)
   at Pchp.CodeAnalysis.Semantics.Graph.GraphRewriter.VisitCFG(ControlFlowGraph x)
   at Pchp.CodeAnalysis.FlowAnalysis.Passes.TransformationRewriter.TryTransform(DelayedTransformations delayedTransformations, SourceRoutineSymbol routine)
   at Pchp.CodeAnalysis.SourceCompiler.<>c__DisplayClass28_0.<TransformMethods>b__0(SourceRoutineSymbol m)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)

```

**Comment by jakubmisek** [comment]
fixed with #588 thanks!
