### ISSUE TITLE
Cloning object with reference field causes assertion failure

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#606]
Test case:
```php
class A {
  var $p;

  public function __construct() {
    $var = 0;
    $this->p =& $var;
  }
}

clone new A;
```

Debug output (supposing `Peachpie.Runtime` is compiled under the `Debug` configuration):
```
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----

---- Assert Long Message ----

   at Pchp.Core.Operators.SetValue(PhpValue& target, PhpValue value) in C:\iolevel\peachpie\src\Peachpie.Runtime\Operators.cs:line 222
   at lambda_method(Closure , Context , Object , PhpValue )
   at Pchp.Core.Reflection.PhpPropertyInfo.ClrFieldProperty.SetValue(Context ctx, Object instance, PhpValue value) in C:\iolevel\peachpie\src\Peachpie.Runtime\Reflection\PhpPropertyInfo.cs:line 112
   at Pchp.Core.Reflection.Serialization.MemberwiseClone(PhpTypeInfo tinfo, Object source, Object target) in C:\iolevel\peachpie\src\Peachpie.Runtime\Reflection\Serialization.cs:line 45
   at Pchp.Core.Operators.CloneRaw(Context ctx, Object value) in C:\iolevel\peachpie\src\Peachpie.Runtime\Operators.cs:line 1428
   at Pchp.Core.Operators.Clone(Context ctx, Object value) in C:\iolevel\peachpie\src\Peachpie.Runtime\Operators.cs:line 1402
...
```

**Comment by jakubmisek** [comment]
note: `clone` dereferences cloned properties

**Comment by roberthusak** [comment]
> note: `clone` dereferences cloned properties

It doesn't seem so. Test case:
```php
class A {
  var $p;

  public function __construct(&$var) {
    $this->p =& $var;
  }
}

function test() {
  $var = 42;
  $a = new A($var);
  $b = clone $a;
  $var = 24;
  echo $b->p;
}

test();
```
Expected (PHP output): `24`
Actual: `42`

Should I create a new issue or reopen this one?
