### ISSUE TITLE
curl_getinfo() results in NullReferenceException

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#612]
In my project, I have something like this:

```php
$response  = curl_exec($ch);
$curl_info = curl_getinfo($ch);
````

The `curl_getinfo()` function, when called without the second optional argument, should "return an associative array", according to the [php documentation](https://www.php.net/manual/en/function.curl-getinfo.php).

However, Peach Pie during runtime throws an **`System.NullReferenceException`** exception:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Peachpie.Library.Network.CURLFunctions.curl_getinfo(CURLResource ch, Int32 opt)
   at <Root>Project_name/core.Project_name_php.cURL_test(Context <ctx>, PhpValue URL) in C:\Users\David\Workspace\PHP-CLI\Project_name\core\Project_name.php:line 1025
   at Pchp.Core.PhpCallback.Invoke(Context ctx, PhpValue[] arguments)
   at Pchp.Library.Functions.call_user_func(Context ctx, IPhpCallable function, PhpValue[] args)
   at Pchp.Library.Functions.call_user_func_array(Context ctx, IPhpCallable function, PhpArray args)
   at <Root>Project_name/Tools.startup_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Users\David\Workspace\PHP-CLI\Project_name\Tools\startup.php:line 95
   at <Script>.Main(String[] args)
```

Also, running `var_dump($ch);` returns `resource(8) of type (curl)`, as expected.

What should I do to resolve this issue?

Related: #210

**Comment by DRSDavidSoft** [comment]
I suspect that the last two lines of the following may be to blame:
https://github.com/peachpiecompiler/peachpie/blob/0fc34d5ccfb1a3a878b88249de709ac610d6d2f6/src/Peachpie.Library.Network/CURLFunctions.cs#L167-L170

This is because the `CURLINFO_REDIRECT_URL` also causes the null exception.

**Comment by jakubmisek** [comment]
thank you @DRSDavidSoft , the condition is inverted!

**Comment by DRSDavidSoft** [comment]
@jakubmisek Thanks for the fast response! 😄 

I have also found another issue with the `curl_getinfo()`, in the #613 issue.
