### ISSUE TITLE
error : Sequence contains no elements

### ISSUE THREAD

**Issue by 39ff** [peachpiecompiler/peachpie#643]
Errors

```
1>------ Build started: Project: TestPeachPie, Configuration: Debug Any CPU ------
1>PeachPie PHP Compiler version 0.9.46+92daf0f5043a80a36bc511ab6826ab3cedb59760
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error : Sequence contains no elements
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error :    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error :    at Pchp.CodeAnalysis.Symbols.CoreTypes.Update(AssemblySymbol coreass)
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error :    at Pchp.CodeAnalysis.PhpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(PhpCompilation compilation)
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error :    at Pchp.CodeAnalysis.PhpCompilation.GetBoundReferenceManager()
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error :    at Pchp.CodeAnalysis.PhpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken)
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
1>C:\Users\kouhei\.nuget\packages\peachpie.net.sdk\0.9.46\build\Peachpie.NET.Core.Sdk.targets(224,5): error :    at Peachpie.NET.Sdk.Tools.BuildTask.Execute()
1>Done building project "TestPeachPie.msbuildproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Composer
```
composer require guzzlehttp/guzzle
```

Code
```
<?php
require 'vendor/autoload.php';
use GuzzleHttp\Client;

$client = new Client();
$response = $client->request('GET', 'https://httpbin.org/ip');
echo $response->getStatusCode();
```

msbuildproj
```
<Project Sdk="Peachpie.NET.Sdk/0.9.46">
  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <LangVersion>7.2</LangVersion>
    <StartupObject>program.php</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.php"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Peachpie.Library.Network" Version="0.9.800" />
    <PackageReference Include="Peachpie.Library.RegularExpressions" Version="1.1.0" />
    <PackageReference Include="Peachpie.Library.Scripting" Version="0.9.800" />
    <PackageReference Include="Peachpie.Library.XmlDom" Version="0.9.800" />
  </ItemGroup>
</Project>
```

**Comment by jakubmisek** [comment]
thank you, try consolidate the versions of `Peachpie.***` ... Use `0.0.800` everywhere, or don't specify the references explicitly at all (not needed):

```xml
<Project Sdk="Peachpie.NET.Sdk/0.9.800">
  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <LangVersion>7.2</LangVersion>
    <StartupObject>program.php</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.php"/>
  </ItemGroup>
</Project>
```

**Comment by 39ff** [comment]
Hi Thanks. Build successfully, but not working
```
System.NotImplementedException
  HResult=0x80004001
  Message=The method or operation is not implemented.
  Source=Peachpie.Library
  StackTrace:
   at Pchp.Library.Web.idn_to_ascii(String domain, Int32 options, Int32 variant, PhpArray& idna_info)
   at <Root>vendor/guzzlehttp/guzzle/src.functions_php.GuzzleHttp._idn_uri_convert(Context <ctx>, UriInterface uri, PhpValue options) in C:\Users\kouhei\source\repos\TestPeachPie\TestPeachPie\vendor\guzzlehttp\guzzle\src\functions.php:line 362
   at GuzzleHttp.Client.buildUri(PhpValue uri, PhpArray config) in C:\Users\kouhei\source\repos\TestPeachPie\TestPeachPie\vendor\guzzlehttp\guzzle\src\Client.php:line 220
   at GuzzleHttp.Client.requestAsync(PhpValue method, PhpValue uri, PhpArray options) in C:\Users\kouhei\source\repos\TestPeachPie\TestPeachPie\vendor\guzzlehttp\guzzle\src\Client.php:line 155
   at GuzzleHttp.Client.request(PhpValue method, PhpValue uri, PhpArray options) in C:\Users\kouhei\source\repos\TestPeachPie\TestPeachPie\vendor\guzzlehttp\guzzle\src\Client.php:line 183
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at <Root>.program_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Users\kouhei\source\repos\TestPeachPie\TestPeachPie\program.php:line 6
   at <Script>.Main(String[] args)

```

**Comment by jakubmisek** [comment]
Thank you for confirmation.

`idn_to_ascii` with the last parameter is not yet implemented
https://github.com/peachpiecompiler/peachpie/blob/0c8d013e63c28ee70b44e4f1dd53dd07308c2414/src/Peachpie.Library/Web.cs#L1055-L1058

please file a new issue for this function, possibly with a small test case.
