### ISSUE TITLE
Process terminated. Assertion Failed

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#645]
### Description
I'm getting a **"Process terminated. Assertion Failed"** message
```
   at Pchp.Core.Operators.SetValue(PhpValue& target, PhpValue value)
   at Pchp.Core.OrderedDictionary.AssignValue(IntStringKey key, PhpValue value)
   at Pchp.Core.PhpArray.SetItemValue(IntStringKey key, PhpValue value)
```

What can I do to debug this issue?

**Comment by jakubmisek** [comment]
Thanks, please post a stack trace - if it is caused by a PHP code or an improper of C# API ?

In the first case, the line of PHP code causing this would help.

**Comment by DRSDavidSoft** [comment]
Since I'm doing a `call_user_func_array()`, I'm not sure how I can detect the issue.

### Here's the full stack trace:
```cs
Process terminated. Assertion Failed
   at Pchp.Core.Operators.SetValue(PhpValue& target, PhpValue value)
   at Pchp.Core.OrderedDictionary.AssignValue(IntStringKey key, PhpValue value)
   at Pchp.Core.PhpArray.SetItemValue(IntStringKey key, PhpValue value)
   at <Root>REPL.repl_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Users\David\Workspace\PHP-CLI\REPL\repl.php:line 179
   at <Root>REPL.repl_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.program_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Users\David\Workspace\PHP-CLI\program.php:line 7
   at <Script>.Main(String[] args)
```

### Here's line 179 of repl.php:
```php
if ( is_callable($args[0]) )	$res = call_user_func_array( $args[0], $args[1] );
```

**Comment by jakubmisek** [comment]
thanks, it's probably a one line above (an assignment to an array item?)

**Comment by DRSDavidSoft** [comment]
@jakubmisek I don't believe so, as I don't assign values to the array members.

```php
$command = trim(fgets($handle));
$args = explode(' ', $command, 2);
```

**Comment by jakubmisek** [comment]
Nice! I'll look into this, it makes sort of sense.

Shouldn't the function signature be annotated with `&` as well? otherwise the reference is pointless here.

**Comment by jakubmisek** [comment]
good, it is a bug in compiler .. it does not de-references the return value causing wrong assumptions afterwards

I'll create an issue for that! thanks

```c#
static PhpValue do_something([NotNull] PhpArray an_array) {
	PhpException.ThrowIfArgumentNull(an_array, 1);
	PhpAlias alias;
	PhpValue ret2 = (alias = an_array.EnsureItemAlias(new IntStringKey("something")));
	return alias; // <-- bug, value must be de-referenced, alias must not be returned from this function
}
```

**Comment by DRSDavidSoft** [comment]
@jakubmisek You're absolutely right, I only wrote that just to demonstrate the issue.

Thanks for finding out the problem!

**Comment by jakubmisek** [comment]
thanks @DRSDavidSoft , great test case!

**Comment by bfistein** [comment]
@DRSDavidSoft do you have a Twitter account? Your work as been extremely helpful and we really appreciate your contributions, so we'd like to give you a shout out.

**Comment by DRSDavidSoft** [comment]
@bfistein Thank you, I would appreciate it! I'd be glad to be of help. Yes, I do have Twitter, with the same username (@DRSDavidSoft), although I'm more active on other platforms.
