### ISSUE TITLE
Issue with saveHTML() with DOMText

### ISSUE THREAD

**Issue by DRSDavidSoft** [peachpiecompiler/peachpie#650]
### Example code
```php
function innerHTML(DOMNode $DOMNode = NULL) {
	$innerHTML = '';
	$children  = $DOMNode->childNodes;

	foreach($children as $child) {
		print_r("type: " . get_class($child));
		$innerHTML .= $DOMNode->ownerDocument->saveHTML($child);
	}

	return $innerHTML;
}

$dom = new DOMDocument;
@$dom->loadHTML("<html ..... /html>"); // example html

$some_str  = innerHTML( $dom->getElementById("some_id") );
```

### Expected behavior
The `saveHTML()` method should work fine on both `DOMElement` and `DOMText` types (children of the passed `DOMNode`

### Actual results
- `saveHTML()` fails with `DOMText`.
- `saveHTML()` works only with `DOMElement`.

### Stack trace
```cs
Unhandled exception. System.InvalidOperationException: Token Text in state Start would result in an invalid XML document. Make sure that the ConformanceLevel setting is set to ConformanceLevel.Fragment or ConformanceLevel.Auto if you want to write an XML fragment.
   at System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition(Token token, State currentState)
   at System.Xml.XmlWellFormedWriter.AdvanceState(Token token)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlText.WriteTo(XmlWriter w)
   at Peachpie.Library.XmlDom.DOMDocument.SaveXMLInternal(Context ctx, Stream outStream, DOMNode node, Boolean omitXmlDeclaration)
   at Peachpie.Library.XmlDom.DOMDocument.saveHTML(Context ctx, DOMNode node)
   at <Root>Project/core.Project_php.innerHTML(Context <ctx>, DOMNode DOMNode) in C:\Users\David\Workspace\PHP-CLI\Project\core\Project.php:line 1592
```

**Comment by DRSDavidSoft** [comment]
@jakubmisek Can you have a look at this, please?

**Comment by jakubmisek** [comment]
maybe the recent fix in `getElementById` changed something, but I'm getting `System.NullReferenceException` which is correct since `$DOMNode` is `null`

**Comment by DRSDavidSoft** [comment]
@jakubmisek I think there might be an issue with the way `getElementById` works

nontheless, please use the following test case instead, while I check the issues of `getElementById` .

### New test case
```php
function innerHTML(DOMNode $DOMNode = NULL) {
	// if ( $DOMNode == NULL ) return '';

	$innerHTML = '';
	$children  = $DOMNode->childNodes;

	foreach($children as $child) {
		print_r("type: " . get_class($child)); echo PHP_EOL;
		$innerHTML .= $DOMNode->ownerDocument->saveHTML($child);
	}

	return trim($innerHTML);
}

$dom = new DOMDocument;
@$dom->loadHTML("<html> <div id='some_id'> foo <span>bar</span> baz <i class='icon'></i> </div> </html>"); // example html

$domElement = $dom->getElementsByTagName('div')[0];
// $domElement = $dom->getElementById("some_id");
if ( $domElement == null ) die("FAULT: null detected");
print_r("id: " . $domElement->getAttribute('id')); echo str_repeat(PHP_EOL, 2);

$some_str   = innerHTML($domElement);
var_dump($some_str);
```

### PHP results
```
id_php: some_id

type: DOMText
type: DOMElement
type: DOMText
type: DOMElement
type: DOMText
string(45) "foo <span>bar</span> baz <i class="icon"></i>"
```

### PeachPie results
```
id: some_id

type: DOMText
Unhandled exception. System.InvalidOperationException: Token Text in state Start would result in an invalid XML document. Make sure that the ConformanceLevel setting is set to ConformanceLevel.Fragment or ConformanceLevel.Auto if you want to write an XML fragment.
   at System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition(Token token, State currentState)
   at System.Xml.XmlWellFormedWriter.AdvanceState(Token token)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlText.WriteTo(XmlWriter w)
   at Peachpie.Library.XmlDom.DOMDocument.SaveXMLInternal(Context ctx, Stream outStream, DOMNode node, Boolean omitXmlDeclaration)
   at Peachpie.Library.XmlDom.DOMDocument.saveHTML(Context ctx, DOMNode node)
   at <Root>.program_php.innerHTML(Context <ctx>, DOMNode DOMNode) in C:\Users\David\Workspace\PHP-CLI\program.php:line 22
   at <Root>.program_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Users\David\Workspace\PHP-CLI\program.php:line 37
   at <Script>.Main(String[] args)
```
