### ISSUE TITLE
VS debugger shows error when inspecting `PhpValue`

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#655]
callstack:
```
   at Pchp.Core.PhpValue.get_TypeCode() in \src\Peachpie.Runtime\PhpValue.cs:line 235
   at Pchp.Core.PhpValue.ToClr() in \src\Peachpie.Runtime\PhpValue.cs:line 545
   at Pchp.Core.PhpValue.PhpValueDebugView.get_DebugValue() in \src\Peachpie.Runtime\PhpValue.DebugView.cs:line 33
```

![image](https://user-images.githubusercontent.com/842150/73653983-d1f2c180-468a-11ea-9c8e-67f549c8b885.png)

**Comment by jakubmisek** [comment]
fixed with recent changed
