### ISSUE TITLE
dompdf fails with "no block-level parent found"

### ISSUE THREAD

**Issue by Remo** [peachpiecompiler/peachpie#682]
Got a `composer.json` like this:

```
{
    "require": {
        "dompdf/dompdf": "^0.8.5"
    }
}
```

A `program.php` with this content:
```php
<?php
use Dompdf\Dompdf;

require 'vendor/autoload.php';

$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

$output = $dompdf->output();
file_put_contents('test.pdf', $output);
```

And a project file like this:
```
<Project Sdk="Peachpie.NET.Sdk/0.9.800">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <StartupObject>program.php</StartupObject>
    <Description>Simpliest PHP project for .NET Core, a console application.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.php" />
    <Compile Remove="**/test/**/*.php" />
    <Compile Remove="**/tests/**/*.php" />
  </ItemGroup>
  
</Project>
```

When I run it, it fails with this exception:

```
Unhandled Exception: Dompdf.Exception: No block-level parent found.  Not good.
   at Dompdf.Positioner.Inline.position(AbstractFrameDecorator frame) in C:\work\peachpie-dompdf\vendor\dompdf\dompdf\src\Positioner\Inline.php:line 47
   at CallSite.Target(Closure , CallSite , PhpValue , Context , AbstractFrameDecorator )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Dompdf.FrameDecorator.AbstractFrameDecorator.position() in C:\work\peachpie-dompdf\vendor\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php:line 875
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at Dompdf.FrameReflower.Text.reflow(Block block) in C:\work\peachpie-dompdf\vendor\dompdf\dompdf\src\FrameReflower\Text.php:line 371
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at Dompdf.FrameDecorator.AbstractFrameDecorator.reflow(Block block) in C:\work\peachpie-dompdf\vendor\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php:line 896
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at Dompdf.FrameReflower.Page.reflow(Block block) in C:\work\peachpie-dompdf\vendor\dompdf\dompdf\src\FrameReflower\Page.php:line 142
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpValue& )
   at Dompdf.FrameDecorator.AbstractFrameDecorator.reflow(Block block) in C:\work\peachpie-dompdf\vendor\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php:line 896
   at Dompdf.Dompdf.render() in C:\work\peachpie-dompdf\vendor\dompdf\dompdf\src\Dompdf.php:line 859
   at CallSite.Target(Closure , CallSite , PhpValue , Context , CallerTypeParam )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at <Root>.program_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\work\peachpie-dompdf\program.php:line 14
   at <Script>.Main(String[] args)
```

**Comment by jakubmisek** [comment]
thank you @Remo !

This issue has been already fixed within latest commits; the problem was `loadHTML` to work properly on non-compliant XML data.

Still this example will produce an empty page, because
```php
$dompdf->loadHtml('hello world');
```
is treated as `<html>hello world</html>`

`loadHtml` should probably treat it as a `<body>` content (TODO)

**Comment by jakubmisek** [comment]
closing since in current `master` it's fixed already
