### ISSUE TITLE
Issue referencing C# project from PHP project

### ISSUE THREAD

**Issue by Alexander882** [peachpiecompiler/peachpie#715]
Hi, I'm trying to get an existing project up and running on peach pie, but I'm having an issue when trying to build.
I get the following error when adding a reference from my PHP project to a C# project.
The C# project contains a single, empty class, and the php project contains a couple hundred files. If i remove the reference to the C# project, or just remove the C# file the compilation succeeds

```
Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Pchp.CodeAnalysis.Symbols.CoreMethod.ResolveSymbol(NamedTypeSymbol declaringType)
   at Pchp.CodeAnalysis.Symbols.CoreMember`1.get_Symbol()
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvertToPhpArray(TypeSymbol from, TypeRefMask fromHint)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(TypeSymbol from, TypeRefMask fromHint, TypeSymbol to)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitLoadArgument(ParameterSymbol targetp, BoundExpression expr, List`1 writebacks)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitCall(ILOpCode code, MethodSymbol method, BoundExpression thisExpr, ImmutableArray`1 arguments, BoundTypeRef staticType)
   at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.EmitDirectCall(CodeGenerator cg, ILOpCode opcode, MethodSymbol method, BoundTypeRef staticType)
   at Pchp.CodeAnalysis.Semantics.BoundRoutineCall.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.EmitConvert(BoundExpression expr, TypeSymbol to)
   at Pchp.CodeAnalysis.Semantics.Graph.ConditionalEdge.Generate(CodeGenerator cg)
   at Pchp.CodeAnalysis.Semantics.Graph.Edge.Pchp.CodeAnalysis.CodeGen.IGenerator.Generate(CodeGenerator cg)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.Semantics.Graph.StartBlock.Emit(CodeGenerator cg)
   at Pchp.CodeAnalysis.Semantics.Graph.BoundBlock.Pchp.CodeAnalysis.CodeGen.IGenerator.Generate(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateBlock(BoundBlock block)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.LocalScope.ContinueWith(BoundBlock block)
   at Pchp.CodeAnalysis.CodeGen.CodeGenerator.GenerateScope(BoundBlock block, ScopeType type, Int32 to)
   at Pchp.CodeAnalysis.Symbols.SourceRoutineSymbol.Generate(CodeGenerator cg)
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.<>c__DisplayClass1_0.<GenerateMethodBody>b__0(ILBuilder builder)
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol routine, Action`1 builder, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
   at Pchp.CodeAnalysis.CodeGen.MethodGenerator.GenerateMethodBody(PEModuleBuilder moduleBuilder, SourceRoutineSymbol routine, Int32 methodOrdinal, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, Boolean emittingPdb)
   at Pchp.CodeAnalysis.SourceCompiler.EmitMethodBody(SourceRoutineSymbol routine)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )	
```

**Comment by Alexander882** [comment]
Actually, I can also make the compilation succeed by removing some of the php files, although which files i remove does not seem to matter

**Comment by jakubmisek** [comment]
Hi, this seems like unconsolidated reference versions, i.e.
your PeachPie project is referencing `Peachpie.NET.Sdk/VERSION` and your C# project references `Peachpie...` of some `VERSION`.

Those versions must match exactly.

---
fyi the error is caused by a specific compiler version expecting a certain version of `Peachpie.Runtime` reference, but provided reference is different.

**Comment by Alexander882** [comment]
Ah, great. Downgrading the NuGet package to match the SDK fixed it. Thanks!

**Comment by jakubmisek** [comment]
good! you can also upgrade the SDK :)
