### ISSUE TITLE
Problematic handling of session cookie when custom session handler is used

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#718]
As a test case, let's have the following as the single PHP script in an Asp.NET Core website (`FileSessionHandler` is taken from the [PHP manual](https://www.php.net/manual/en/function.session-set-save-handler.php)):
```php
<?php

class FileSessionHandler implements SessionHandlerInterface
{
  private $savePath;

  function open($savePath, $sessionName)
  {
    $this->savePath = $savePath;
    if (!is_dir($this->savePath)) {
      mkdir($this->savePath, 0777);
    }

    return true;
  }

  function close()
  {
    return true;
  }

  function read($id)
  {
    return (string)@file_get_contents("$this->savePath/sess_$id");
  }

  function write($id, $data)
  {
    return file_put_contents("$this->savePath/sess_$id", $data) === false ? false : true;
  }

  function destroy($id)
  {
    $file = "$this->savePath/sess_$id";
    if (file_exists($file)) {
      unlink($file);
    }

    return true;
  }

  function gc($maxlifetime)
  {
    foreach (glob("$this->savePath/sess_*") as $file) {
      if (filemtime($file) + $maxlifetime < time() && file_exists($file)) {
        unlink($file);
      }
    }

    return true;
  }
}

session_set_save_handler(new FileSessionHandler(), true);
session_start();
echo session_id() ."\n";
```

Expected behavior: The session ID stays the same between subsequent page reloads and is stored as a cookie.

Actual behavior: The session ID is different for each page load, not stored in cookies and the following exception is thrown due to setting the cookie from the call of `session_write_close` (registered as a shutdown handler by `session_set_save_handler`):
```
System.InvalidOperationException: Headers are read-only, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
   at Microsoft.AspNetCore.Http.ResponseCookies.Append(String key, String value, CookieOptions options)
   at Peachpie.AspNetCore.Web.RequestContextCore.Pchp.Core.IHttpPhpContext.AddCookie(String name, String value, Nullable`1 expires, String path, String domain, Boolean secure, Boolean httpOnly)
   at Pchp.Library.Session.UserHandlerInternal.Persist(IHttpPhpContext webctx, PhpArray session)
   at Pchp.Core.PhpSessionHandler.CloseSession(Context ctx, IHttpPhpContext webctx, Boolean abandon)
   at Pchp.Library.Session.session_commit(Context ctx)
   at Pchp.Library.Session.session_write_close(Context ctx)
   at Pchp.Core.Context.ProcessShutdownCallbacks()
   at Pchp.Core.Context.Dispose()
   at Peachpie.AspNetCore.Web.RequestContextCore.Dispose()
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by jakubmisek** [comment]
seems we have to add at least a dummy cookie into the cookies on `session_start` when a new session is created so aspnet.core (and aspnet) generates and stores the session id.

**Comment by roberthusak** [comment]
I'm suggesting some changes in a PR, which would set the cookie currently set in `Persist` and `Abandon` earlier and with the check of `HeadersSent`. Better check that I don't break anything this way, please :-)

**Comment by roberthusak** [comment]
I'm not sure how exactly we interact with Asp.NET Core sessions, as there is an `AspNetCoreSessionHandler`, which I suppose is not used when `UserHandlerInternal` is used due to `session_set_save_handler`.

**Comment by jakubmisek** [comment]
sadly session lifecycle is not that simple

**Comment by jakubmisek** [comment]
`GetSessionId()` should create the cookie if it's not a new session. Doing so in `Persist()` is too late.

**Comment by jackflyer** [comment]
Is this issue solved? Any way to use only custom SessionHandlerInterface shown as above, instead PeachPie's own internal Implementation?

**Comment by jakubmisek** [comment]
@jackflyer `SessionHandlerInterface` is supported.

Note, when running under *asp.net core*, a session middleware must be added into the application pipeline: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-5.0#configure-session-state
