### ISSUE TITLE
Method not found: 'Void Pchp.Core.IntStringKey..ctor(Int32)'

### ISSUE THREAD

**Issue by PudottaPommin** [peachpiecompiler/peachpie#742]
Hello,

I ran across this problem with installation of [ResponsiveFileManager](https://github.com/gordon-matt/peachpie-responsive-file-manager).  Any tips or suggestions will be appreciated, because I don't have even clue, what could be problem ( if is any problem in original php script or not ).

```
System.MissingMethodException: Method not found: 'Void Pchp.Core.IntStringKey..ctor(Int32)'.
   at <Root>filemanager.dialog_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>filemanager.dialog_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I'm using **.net core 3.1** and
```
    <PackageReference Include="Peachpie.AspNetCore.Web" Version="0.9.970" />
    <PackageReference Include="ResponsiveFileManager" Version="1.2.1" />
```

**Comment by jakubmisek** [comment]
The version of `Peachpie.AspNetCore.Web` must match with the version of `Peachpie.Runtime` used by this `ResponsiveFileManager` which is `0.9.910`.

Change your reference to:
```xml
<PackageReference Include="Peachpie.AspNetCore.Web" Version="0.9.910" />
```

Otherwise Peachpie versions mismatch (their API's are not compatible since it is still in development)
