### ISSUE TITLE
Cannot use indexer for Dictionary<,>

### ISSUE THREAD

**Issue by hez2010** [peachpiecompiler/peachpie#750]
```php
<?php

function main()
{
    $d = new System\Collections\Generic\Dictionary<int, string>;
    $d[5] = "test";
    echo $d[5];
    return;
}

main();

```

throws:
```
Unhandled exception. System.InvalidOperationException: An object of type 'System\Collections\Generic\Dictionary' used as an array
   at Pchp.Core.PhpException.Throw(PhpError error, String message)
   at Pchp.Core.PhpException.Throw(PhpError error, String formatString, String[] args)
   at Pchp.Core.Operators.GetItemValue(Object obj, PhpValue index, Boolean quiet)
   at Pchp.Core.Operators.GetItemValue(PhpValue value, PhpValue index, Boolean quiet)
   at <Root>.program_php.main(Context <ctx>) in C:\Users\hez20\source\repos\PeachPieConsole\program.php:line 7  
   at <Root>.program_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in C:\Users\hez20\source\repos\PeachPieConsole\program.php:line 11
   at <Script>.Main(String[] args)
```

**Comment by jakubmisek** [comment]
thanks!
