### ISSUE TITLE
 session_destroy() on asp.net core is not implemented

### ISSUE THREAD

**Issue by itpleb** [peachpiecompiler/peachpie#788]
```php
        unset($_SESSION);
        session_destroy();
```

```
System.NotImplementedException
  HResult=0x80004001
  Message=The method or operation is not implemented.
  Source=Peachpie.AspNetCore.Web
  StackTrace:
   at Peachpie.AspNetCore.Web.Session.AspNetCoreSessionHandler.Abandon(IHttpPhpContext webctx)
   at Pchp.Core.PhpSessionHandler.CloseSession(Context ctx, IHttpPhpContext webctx, Boolean abandon)
   at Peachpie.AspNetCore.Web.Session.AspNetCoreSessionHandler.CloseSession(Context ctx, IHttpPhpContext webctx, Boolean abandon)
   at Pchp.Library.Session.session_destroy(Context ctx)
   at step1Action#1.getDefaultView() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\modules\Default\actions\step1Action.class.php:line 21
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at ExecutionFilter?1.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 1861
   at System.Dynamic.UpdateDeleSystem.NotImplementedException
  HResult=0x80004001
  Message=The method or operation is not implemented.
  Source=Peachpie.AspNetCore.Web
  StackTrace:
   at Peachpie.AspNetCore.Web.Session.AspNetCoreSessionHandler.Abandon(IHttpPhpContext webctx)
   at Pchp.Core.PhpSessionHandler.CloseSession(Context ctx, IHttpPhpContext webctx, Boolean abandon)
   at Peachpie.AspNetCore.Web.Session.AspNetCoreSessionHandler.CloseSession(Context ctx, IHttpPhpContext webctx, Boolean abandon)
   at Pchp.Library.Session.session_destroy(Context ctx)
   at step1Action#1.getDefaultView() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\modules\Default\actions\step1Action.class.php:line 21
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at ExecutionFilter?1.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 1861
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at SedFilter?0#2.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\filter\SedFilter.class.php:line 38
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at ThdFilter?0#2.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\filter\ThdFilter.class.php:line 36
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at LoginFilter?0#2.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\filter\LoginFilter.class.php:line 7
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at ExecutionTimeFilter#2.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\LaiKeTui\filter\ExecutionTimeFilter.class.php:line 133
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at Controller?2.forward(PhpValue moduleName, PhpValue actionName) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 1035
   at FrontWebController#1.dispatch() in G:\WorkCode\ZX.Shopx\ZX.Shopx\LaiKeTui\controller\FrontWebController.class.php:line 90
   at <Root>install.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\index.php:line 29
   at <Root>install.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
gates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at SedFilter?0#2.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\filter\SedFilter.class.php:line 38
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at ThdFilter?0#2.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\filter\ThdFilter.class.php:line 36
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at LoginFilter?0#2.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\filter\LoginFilter.class.php:line 7
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at ExecutionTimeFilter#2.execute(PhpValue filterChain) in G:\WorkCode\ZX.Shopx\ZX.Shopx\LaiKeTui\filter\ExecutionTimeFilter.class.php:line 133
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at FilterChain?1.execute() in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 2036
   at Controller?2.forward(PhpValue moduleName, PhpValue actionName) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\webapp\_cache\config_compile.conf.php:line 1035
   at FrontWebController#1.dispatch() in G:\WorkCode\ZX.Shopx\ZX.Shopx\LaiKeTui\controller\FrontWebController.class.php:line 90
   at <Root>install.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in G:\WorkCode\ZX.Shopx\ZX.Shopx\install\index.php:line 29
   at <Root>install.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
```

**Comment by jakubmisek** [comment]
implemented in https://github.com/peachpiecompiler/peachpie/commit/0afaffd04b81be31e6a9d355798a20b796a8a8d8
