### ISSUE TITLE
Call to undefined method System\NotImplementedException::getMessage(

### ISSUE THREAD

**Issue by maikebing** [peachpiecompiler/peachpie#855]
`errormsg = $exception->getMessage(); `
Pchp.Library.Spl.Error:“Call to undefined method System\NotImplementedException::getMessage()”

**Comment by jakubmisek** [comment]
Do you have a stack trace of the `$exception`? Is it caused by https://github.com/peachpiecompiler/peachpie/issues/854 ?

**Comment by maikebing** [comment]
I'm trying to debug this project, 
https://github.com/maikebing/DiscuzX

**Comment by maikebing** [comment]
yes , Is it caused by  

 at Pchp.Core.PhpException.UndefinedMethodCalled(String typeName, String funcName)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at discuz_error.exception_error(Context <ctx>, PhpValue exception) in D:\Works\DiscuzX\upload\source\class\discuz\discuz_error.php:line 135
   at core.handleException(Context <ctx>, PhpValue exception) in D:\Works\DiscuzX\upload\source\class\class_core.php:line 121
   at Pchp.Core.Reflection.PhpMethodInfo.Invoke(Context ctx, Object target, PhpValue[] arguments)
   at Pchp.Core.Reflection.PhpMethodInfo.<get_PhpCallable>b__16_0(Context ctx, PhpValue[] args)
   at Pchp.Core.Context.OnUnhandledException(Exception exception)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.<>c__DisplayClass14_0.<InvokeScriptAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by jakubmisek** [comment]
thank you, it would happen when a regular .NET exception gets into a PHP code. So with the #854 fixed, it won't happen in this case again
