### ISSUE TITLE
mysqlconnection alredy in use

### ISSUE THREAD

**Issue by BKSoftCraft** [peachpiecompiler/peachpie#990]
`````````php
<?php
require "dbconn.php";                    //Connnection File
$flag = 1;
$conn->beginTransaction();
$sql = "INSERT INTO t1 (name) VALUES (:name)";
$stmt1 = $conn->prepare($sql);
$i = 1;
while ($i <= 5) {
    $rs = $stmt1->execute([':name' => $i]);
    if (!$rs) {
        $flag = 0;
        break;
    }
    $i++;
}
if ($flag == 0) {
    $conn->rollBack();
} else {
    if (!$conn->commit()) {
        echo "Commit Fail";
    } else {
        echo "Success";
    }
}

// I am Getting mysqlConnection is alredy in use at commit. Please Help me to getover this problem ?????
'

**Comment by BKSoftCraft** [comment]
`require "dbconn.php";  // Connection File
$flag = 1;
$conn->beginTransaction();
$sql = "INSERT INTO t1 (name) VALUES (:name)";
$stmt1 = $conn->prepare($sql);
$i = 1;
while ($i <= 5) {
    $rs = $stmt1->execute([':name' => $i]);
    if (!$rs) {
        $flag = 0;
        break;
    }
    $i++;
}
if ($flag == 0) {
    $conn->rollBack();
} else {
    if (!$conn->commit()) {
        echo "Commit Fail";
    } else {
        echo "Success";
    }
}
`

**Comment by jakubmisek** [comment]
seems like a bug; is it `PDOConnection` object? Do you have the full stack trace of the exception?

**Comment by BKSoftCraft** [comment]
yes $conn is PDOConnection Object

**Comment by BKSoftCraft** [comment]
''''
System.InvalidOperationException
  HResult=0x80131509
  Message=This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
  Source=MySqlConnector
  StackTrace:
   at MySqlConnector.Core.ServerSession.StartQuerying(ICancellableCommand command) in /_/src/MySqlConnector/Core/ServerSession.cs:line 294
   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext() in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.MySqlCommand.<ExecuteNonQueryAsync>d__69.MoveNext() in /_/src/MySqlConnector/MySqlCommand.cs:line 271
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MySqlConnector.MySqlTransaction.<CommitAsync>d__2.MoveNext() in /_/src/MySqlConnector/MySqlTransaction.cs:line 39
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MySqlConnector.MySqlTransaction.Commit() in /_/src/MySqlConnector/MySqlTransaction.cs:line 21
   at Peachpie.Library.PDO.PDO.commit()
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at <Root>.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in F:\xampp\htdocs\T1\Test\Test\Test\index.php:line 51
   at <Root>.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script, String path_info)

  This exception was originally thrown at this call stack:
    [External Code]
    <Root>.index_php.<Main>(Pchp.Core.Context, Pchp.Core.PhpArray, object, System.RuntimeTypeHandle) in index.php
    [External Code]

**Comment by BKSoftCraft** [comment]
Thanks for reply ,I think no one going to reply and my project is going to dead

**Comment by BKSoftCraft** [comment]
'''''''php
// index.php
<?php
require "dbconn.php";
$flag = 1;
$conn->beginTransaction();
$sql = "INSERT INTO t1 (name) VALUES (:name)";
$stmt1 = $conn->prepare($sql);
$i = 1;
while ($i <= 5) {
    $rs = $stmt1->execute([':name' => $i]);
    if (!$rs) {
        $flag = 0;
        break;
    }
    $i++;
}
if ($flag == 0) {
    $conn->rollBack();
} else {
    if (!$conn->commit()) {
        echo "Commit Fail";
    } else {
        echo "Success";
    }
}

// dbconn.php
<?php
try {
    $server = "localhost";
    $username = "root";
    $password = "";

    $conn = new PDO("mysql:host=$server;dbname=test1", $username, $password);
    $conn->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
} catch (Exception $e) {
    echo "Failed: " . $e->getMessage();
}

**Comment by BKSoftCraft** [comment]
is there any solution for it ?

**Comment by jakubmisek** [comment]
yes, thanks for reminding us; this should be fixed with https://github.com/peachpiecompiler/peachpie/commit/17cbde79f7d7367da8277f36a4203ace34fae16f

**Comment by BKSoftCraft** [comment]
So now problem solved ?

**Comment by BKSoftCraft** [comment]
> yes, thanks for reminding us; this should be fixed with [17cbde7](https://github.com/peachpiecompiler/peachpie/commit/17cbde79f7d7367da8277f36a4203ace34fae16f)

How to implement this changes in existing project

**Comment by jakubmisek** [comment]
you can either wait for the next release or use the latest builds as described at https://docs.peachpie.io/scenarios/intermediate/nightly-builds/

**Comment by BKSoftCraft** [comment]
> you can either wait for the next release or use the latest builds as described at https://docs.peachpie.io/scenarios/intermediate/nightly-builds/

Is this Builds Are Bugs Free ??

**Comment by BKSoftCraft** [comment]
> you can either wait for the next release or use the latest builds as described at https://docs.peachpie.io/scenarios/intermediate/nightly-builds/

Is it safe for production uses ?

**Comment by jakubmisek** [comment]
it passes tests, so something like prerelease-safe

**Comment by BKSoftCraft** [comment]
> it passes tests, so something like prerelease-safe

About how much it take for next release any idea ?

**Comment by BKSoftCraft** [comment]
> it passes tests, so something like prerelease-safe

Any Guide to make Android App with Peach pie ???

**Comment by jakubmisek** [comment]
> > it passes tests, so something like prerelease-safe
> 
> Any Guide to make Android App with Peach pie ???

please start a new thread if you have questions not related to "mysqlconnection alredy in use"
